### ISSUE TITLE
OnClosed does not work

### ISSUE THREAD

**Issue by fob71** [doghappy/socket.io-client-csharp#1]
Hi dogHappy... nice work

When I connect to server everything is ok, it connects, it emits, but when server disconnect the client, event onClose isn't fired.

**Comment by doghappy** [comment]
@fob71 Thank you for your feedback. I'm checking.

**Comment by doghappy** [comment]
@fob71 I've fixed it. Can you pull code try it again? If there's any problems, you can give it back again. Thanks

**Comment by fob71** [comment]
no, it's not working for me. 

When I close nodejs server, client does not detect the disconnection.

Also, I have been debbuging the code, and I have found issues with Regex check.

I use:
  node: v10.16.0
  socket.io: 2.2.0
  express: 4.17.1

Thanks

**Comment by doghappy** [comment]
https://github.com/doghappy/socket.io-client-csharp/blob/f530f118968d75903baa452b3b99df18062a22af/SocketIOClient/SocketIO.cs#L89-L97

I added this code, and I think it's useful.

**Comment by doghappy** [comment]
I fixed :D. pushed.

The reason for the problem is that we only used one thread to listen `ReceiveAsync()`. But If the SocketIO server aborted, `ReceiveAsync()` will be stuck.

To fix this problem, I created another thread to listen Socket State.

Do you have a better way?

**Comment by fob71** [comment]
the issue has been fixed... client detects server dicsonnection fine
