### ISSUE TITLE
Callback is not called when EmitAsync is called on a connection with a Room

### ISSUE THREAD

**Issue by muscla87** [doghappy/socket.io-client-csharp#10]
As explained in the title. I've already fixed the problem in your library and updated tests and server. Please if you can add me as Contributor I can push the branch with the fix and create pull request that you can evaluate to integrate in master. 

This is the testcase that fails with the current version:
```
[TestMethod]
public async Task CallbackWithRoomTest()
{
	string text = string.Empty;
	string guid = Guid.NewGuid().ToString();
	var client = new SocketIO("http://localhost:3000/path");
	await client.ConnectAsync();
	await Task.Delay(1000);
	bool callbackCalled = false;
	await client.EmitAsync("callback", guid, async res =>
	{
		text = res.Text;
		callbackCalled = true;
		await client.CloseAsync();
	});
	await Task.Delay(1000);
	Assert.IsTrue(callbackCalled, "Callback was not called");
	Assert.AreEqual($"\"{guid} - server/path\"", text);
}
```
And don't forget to update the App.js on the node server to respond to the "callback" message on the Room "path":

```
client.on('callback', (data, fn) => {
        fn(data + " - server/path");
    });
```

Thank you

**Comment by doghappy** [comment]
Awesome, I have added you to the list of contributors

**Comment by doghappy** [comment]
[Merged](https://github.com/doghappy/socket.io-client-csharp/pull/11)
