### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by dhpanteon** [doghappy/socket.io-client-csharp#100]
If their is no internet connection and their are multiple device connected under same network. 

1) Does all devices can communicate without internet using local network automatically?
2) When internet is back, Does it automatically connect over the internet for all devices?

**Comment by doghappy** [comment]
It does not support offline, it is just a client. If you want your application to support offline, you can deploy your server on the LAN and the Internet, and switch to the LAN server when the client loses connection.
