### ISSUE TITLE
How does Curl be specified as WebSocket when connecting to a service

### ISSUE THREAD

**Issue by guaicaiboshi** [doghappy/socket.io-client-csharp#102]
How to specify  "transports": [websocket]
![image](https://user-images.githubusercontent.com/2748771/102295719-f562ea00-3f86-11eb-9020-aced04598071.png)

**Comment by doghappy** [comment]
This library only supports websocket, so you don’t need to specify transports

**Comment by guaicaiboshi** [comment]
> This library only supports websocket, so you don’t need to specify transports

When nodejs Socketio encounters a problem, Connected is always false.

` private string SendData(string accessToken,string eventName,string paramsData)
        {
            ReceivedEventArgs args = null;
            JToken result = null;
            var uri = new Uri(_targetAddress);
            SocketIO _socket = new SocketIO(uri, new SocketIOOptions
            {
                Reconnection=false,
                Query = new Dictionary<string, string>
                 {
                     {"token", accessToken }
                 }
            });
            _socket.OnConnected += async (sender, e) =>
            { 
                Logger.Info($"{_serviceName} {_socket.Id}  connected to server {_targetAddress}");
                await _socket.EmitAsync(eventName, paramsData);
            };
            
            _socket.OnReceivedEvent += (sender, e) =>
            {
                args = e;
                Logger.Info($"{_serviceName} {_socket.Id}  receivedEvent {args.ToJsonString()}");
            };

            _socket.OnDisconnected += (sender, e) =>
            {
                Logger.Info($"{_serviceName} {_socket.Id} disconnected"); 
            };
            _socket.OnReconnectFailed += (sender, ex) =>
            {
                Logger.Info($"{_serviceName} {_socket.Id} reconnectFailed");
            };

            _socket.On(eventName, async response =>
            {
                result = response.GetValue<string>();
                Logger.Info($"{_serviceName} {_socket.Id} On {eventName}:{response}");
            });

            _socket.ConnectAsync();
            Thread.Sleep(1000);  
            _socket.DisconnectAsync();

            Logger.Info($"{_serviceName} {_socket.Id} {result.Value<string>()}");
            Logger.Info($"{_serviceName} {_socket.Id} {args.Response.GetValue<string>()}");
            return args.Response.GetValue<string>();
        }`

**Comment by doghappy** [comment]
Can you describe your problem in detail?
You provided some code, can you provide logs at the same time?

**Comment by guaicaiboshi** [comment]
> Can you describe your problem in detail?
> You provided some code, can you provide logs at the same time?

The _targetAddress is the debug test server, now I need to establish the connection, then send eventName and corresponding data, and then accept the return value to determine if it was successful, now The problem I have is that the packet structure has been assembled, just establish the connection and send it, there is no response.None of the logs here are printed.

**Comment by doghappy** [comment]
You will get at least 2 logs (the last few lines of code). After you call method `SendData()`, does the program throw an exception?

The most important thing is whether the client is connected successfully? 

You can test it with the simplest code:

```cs
       private async Task<string> SendData(string accessToken)
       {
           SocketIO _socket = new SocketIO(_targetAddress, new SocketIOOptions
           {
               Reconnection=false,
               Query = new Dictionary<string, string>
                {
                    {"token", accessToken }
                }
           });
           _socket.OnConnected += (sender, e) =>
           { 
               Logger.Info("*** Connected");
           };

           Logger.Info($"*** before ConnectAsync");
           await _socket.ConnectAsync();
           Logger.Info($"*** after ConnectAsync");
           Thread.Sleep(1000);  
           await _socket.DisconnectAsync();

           Logger.Info($"*** got the result");
           return "got the result";
       }
```

If the connection is successful, the next step is to try to send data.

Are you connected successfully?

**Comment by guaicaiboshi** [comment]
> ```cs
> await SendData();
> ```
Thank you very much for your help. Currently _socket of _socket is _socket.connected is true.but  _socket.On does not receive anything.Nodejs forwarding is ok, now I don't know how to check.My Settings should also be correct:
[Parameters: the token = accessToken
Note that you need to specify Transports as WebSocket when you connect to the service]
`private async Task<string> SendData1(string accessToken, string eventName, string paramsData)
        {
            SocketIO _socket = new SocketIO(_targetAddress, new SocketIOOptions
            {
                Reconnection = false,
                Query = new Dictionary<string, string>
                {
                    {"token", accessToken }
                }
            });
            _socket.OnConnected += (sender, e) =>
            {
                Logger.Info("*** Connected");
            };
            _socket.On(eventName, response =>
            {
                string text = response.GetValue<string>();
                Logger.Info($"*** got the result:" + text);
            });
            Logger.Info($"*** before ConnectAsync");
            await _socket.ConnectAsync();
            Logger.Info($"*** after ConnectAsync");
            if (_socket.Connected)
            {
                await _socket.EmitAsync(eventName, paramsData);
            }
            Thread.Sleep(1000*10);
            await _socket.DisconnectAsync();
            Logger.Info($"*** got the result");
            return "got the result";
        }`

**Comment by doghappy** [comment]
Can you show me the `SendData1()` log?

**Comment by guaicaiboshi** [comment]
> Can you show me the `SendData1()` log?

![image](https://user-images.githubusercontent.com/2748771/102436036-a71b1d00-4052-11eb-9a69-2dbc4652c93d.png)

**Comment by doghappy** [comment]
Cool, it works

try it?

```
        private async Task<string> SendData1(string accessToken, string eventName, string paramsData)
        {
            SocketIO _socket = new SocketIO(_targetAddress, new SocketIOOptions
            {
                Reconnection = false,
                Query = new Dictionary<string, string>
                {
                    {"token", accessToken }
                }
            });
            _socket.OnConnected += (sender, e) =>
            {
                Logger.Info("*** Connected");
                await _socket.EmitAsync(eventName, paramsData);
            };
            _socket.On(eventName, response =>
            {
                string text = response.GetValue<string>();
                Logger.Info($"*** got the result:" + text);
            });
            Logger.Info($"*** before ConnectAsync");
            await _socket.ConnectAsync();
            Logger.Info($"*** after ConnectAsync");
            await _socket.ConnectAsync();
            Thread.Sleep(1000*10);
            await _socket.DisconnectAsync();
            Logger.Info($"*** got the result");
            return "got the result";
        }
```

**Comment by doghappy** [comment]
If `_socket.On(eventName, ...)` does not work, make sure that the returned event name is correct

There is an event here that can monitor all responses. Through it, you know what the server returns

```cs
_socket.OnReceivedEvent += (sender, e) => 
{
    Logger.Info($"*** event name: {e.Event}");
};
```

**Comment by guaicaiboshi** [comment]
> ```cs
>  await _socket.EmitAsync(eventName, paramsData);
> ```

![Uploading image.png…]()

**Comment by guaicaiboshi** [comment]
> ```cs
> _socket.OnReceivedEvent += (sender, e) => 
> {
>     Logger.Info($"*** event name: {e.Event}");
> };
> ```

![image](https://user-images.githubusercontent.com/2748771/102437017-c155fa80-4054-11eb-8842-e84ff788745b.png)

**Comment by doghappy** [comment]
Is there a log about OnReceivedEvent?

**Comment by guaicaiboshi** [comment]
> Is there a log about OnReceivedEvent?

There is no log for OnReceivedEvent .is very confused

**Comment by doghappy** [comment]
How the server sends data determines how you receive data

way 1:

```js
// server
socket.emit("abc", { data: xxx })
```

```cs
// client
socket.On("abc", response => ...)
```

way 2:

```js
// server
socket.on("bac", (name, fn) => {
    // name = ".net core"
    fn({
        result: true,
        message: `test`
    });
});
```

```cs
    await client.EmitAsync("abc", response =>
    {
        result = response.GetValue();
    }, ".net core");
```

Please check how your server returns data

**Comment by guaicaiboshi** [comment]
> How the server sends data determines how you receive data
> 
> way 1:
> 
> ```js
> // server
> socket.emit("abc", { data: xxx })
> ```
> 
> ```cs
> // client
> socket.On("abc", response => ...)
> ```
> 
> way 2:
> 
> ```js
> // server
> socket.on("bac", (name, fn) => {
>     // name = ".net core"
>     fn({
>         result: true,
>         message: `test`
>     });
> });
> ```
> 
> ```cs
>     await client.EmitAsync("abc", response =>
>     {
>         result = response.GetValue();
>     }, ".net core");
> ```
> 
> Please check how your server returns data, and has the server received your request?

Thank you very much for your support.I use socket. IO - client - csharp demo test is no problem, I docking test server is a third party, is also used before colleagues. Net docking failed (without any return), switch to the node to butt, now I want to have a look at the socket. IO - client -csharp whether can csharp, discovery is the server without any response, I temporarily unable to check the server directly, if still not success I will continue to call node.

**Comment by doghappy** [comment]
In fact, you can use Fiddler to detect WS and check what happened to the server and client.

If your client code and service do not contain secrets, maybe I can help you debug.

**Comment by guaicaiboshi** [comment]
> In fact, you can use Fiddler to detect WS and check what happened to the server and client.
> 
> If your client code and service do not contain secrets, maybe I can help you debug.

I'll try it on Fiddler

**Comment by guaicaiboshi** [comment]
> > In fact, you can use Fiddler to detect WS and check what happened to the server and client.
> > If your client code and service do not contain secrets, maybe I can help you debug.
> 
> I'll try it on Fiddler

Thank you very much. The company computer was controlled by IT and could not run Fiddler software. I still called Node to handle IT, thank you again
