### ISSUE TITLE
How To Change / Aply Options Reconnection in Reconnecting Event

### ISSUE THREAD

**Issue by mafaza86** [doghappy/socket.io-client-csharp#103]
I want to protect the server from flood reconnect. By changing the 'Options.ReconnectionDelay' on the OnReconnecting event. The property was changed successfully, but while Reconnect keeps reading the old property, is there a solution? Thank you

```cs
private void ClientIo_OnReconnecting(object sender, int e)
{
	Console.Log($"Reconnecting = {e}x, delay {clientIo.Options.ReconnectionDelay}ms, ac:{clientIo.Options.Reconnection}");
	if (e < 10) clientIo.Options.ReconnectionDelay = e * 1000;
	else clientIo.Options.Reconnection = false;
}
```

**Comment by doghappy** [comment]
There are two properties in Options:

| Option | Default Value | Description |
| :- | :- | :- |
| ReconnectionDelay | 1000 | how long to initially wait before attempting a new reconnection. Affected by +/- `RandomizationFactor`, for example the default initial delay will be between 500 to 1500ms. |
| RandomizationFactor | 0.5 | 0 <= randomizationFactor <= 1 |

**Comment by mafaza86** [comment]
> There are some properties in Options:
> 
> Option	Default Value	Description
> ReconnectionDelay	1000	how long to initially wait before attempting a new reconnection. Affected by +/- `RandomizationFactor`, for example the default initial delay will be between 500 to 1500ms.
> RandomizationFactor	0.5	0 <= RandomizationFactor <= 1
> ReconnectionDelayMax	5000	maximum amount of time to wait between reconnections. Each attempt increases the `ReconnectionDelay` by 2x along with a `RandomizationFactor`.

Thank you @doghappy ...
i want to make this :

1x reconnecting wait : 1000ms
2x reconnecting wait : 2000ms
3x reconnecting wait : 3000ms
4x reconnecting wait : 4000ms
5x reconnecting wait : 5000ms
etc... after this reconnecting wait back to 1000ms;

Can i do it with this option?

**Comment by doghappy** [comment]
Don't support

**Comment by mafaza86** [comment]
> Don't support

Ok thank you, i hope there is a update, can change time ReconnectionDelay from reconnecting event.
Google Talk implement this for auto reconnect.

**Comment by mafaza86** [comment]
Hi @doghappy, i have solved by move get ReconnectionDelay inside the while

#104 thanks
