### ISSUE TITLE
Invalid Port

### ISSUE THREAD

**Issue by ya013ss** [doghappy/socket.io-client-csharp#110]
Hello! I'm trying to do an application that connects to a socket.io server, but i always get this error: "Port is invalid"

Heres my code: 
```cs
var ip = GetSocketIp();
 string uriStr = "http://" + ip.Replace('-', '.') + ":10843";
var uri = new Uri(uriStr);
var socket = new SocketIO(uri, new SocketIOOptions()
{
    Path = ip
});
```

Heres stack trace: 

System.UriFormatException: Nieprawidłowy identyfikator URI: określono nieprawidłowy port.
   w System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   w System.Uri..ctor(String uriString)
   w SocketIOClient.UrlConverter.HttpToWs(Uri httpUri, SocketIOOptions options)
   w SocketIOClient.SocketIO.<ConnectCoreAsync>d__87.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w SocketIOClient.SocketIO.<ConnectAsync>d__86.MoveNext()
--- Koniec śladu stosu z poprzedniej lokalizacji, w której wystąpił wyjątek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   w WebSocketMSP.Program.<Main>d__0.MoveNext() w C:\Users\admin\source\repos\SocketIOTesting\Program.cs:wiersz 46

**Comment by doghappy** [comment]
Can you show the value of `uriStr`? If it contains secret, please replace other words, I just want to know the format.

**Comment by ya013ss** [comment]
Yes,
UriStr is just an ip with dots replaced to -
example:
1-1-1-1

**Comment by doghappy** [comment]
It seems you are using the wrong path value `Path = ip`. The path value will be appended to the url.

**Comment by ovtdex** [comment]
The URL should look like
http://1.1.1.1/1-1-1-1/?transports=websocket
So i dont think its an issue

**Comment by doghappy** [comment]
Thanks, this is my mistake.

use `Path = "/" + ip` instead of

![image](https://user-images.githubusercontent.com/20038914/104667957-25321880-5712-11eb-85be-4eeab5171b17.png)
