### ISSUE TITLE
connect namespace

### ISSUE THREAD

**Issue by thucho0103** [doghappy/socket.io-client-csharp#112]
help me connect ws://127.0.0.1/my-namespace

**Comment by doghappy** [comment]
The example you gave seems to be `Path` instead of `Namespace`, So I recommend you to try the solution below, but I am not sure which works.

**Path**

```cs
var client = new SocketIO("http://127.0.0.1/", new SocketIOOptions
{
    Path = "/my-namespace"
});
```

**Namespace**

```cs
var client = new SocketIO("http://127.0.0.1/my-namespace", new SocketIOOptions
{
    ...
});
```

**Comment by thucho0103** [comment]
i start server socket.io "http://192.162.10.105:1483/nsp" and Client, but client.Connected = false
`var client = new SocketIO(new Uri("http://192.162.10.105:1483/"), new SocketIOOptions
            {
                Path = "/nsp",
            });            
            Console.WriteLine(client.ServerUri);
            Console.WriteLine(client.Namespace);
            Console.WriteLine(client.Connected);`

**Comment by doghappy** [comment]
try it:

```cs
var client = new SocketIO(new Uri("http://192.162.10.105:1483/"), new SocketIOOptions
{
    Path = "/nsp",
});

client.OnConnected += (sender, e) =>
{
    Console.WriteLine(client.Connected);
};
```

**Comment by thucho0103** [comment]
![image](https://user-images.githubusercontent.com/51359206/105009433-0bc00200-5a6d-11eb-90ba-c53963b123cf.png)
I try, but it not working
I used .NETFramework 4.7.2

**Comment by doghappy** [comment]
## Path

generally speaking, you don’t need to set it. 

for example, if you use nginx to deploy socket.io service, if [location](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) is set, then you should also specify Path in SocketIOClient

## namespace

If you want to connect to namespace=message

```cs
var client = new SocketIO(new Uri("http://192.162.10.105:1483/message"), new SocketIOOptions
{
    // Path = "/nsp",
});
```

**Comment by thucho0103** [comment]
thanks, I connected socket.io server but I can handle async function client.ConnectAsync();

**Comment by thucho0103** [comment]
thank you, I has connected socket.io with namespace but I want "join_room", please help me !!!

**Comment by doghappy** [comment]
A room is an arbitrary channel that sockets can join and leave. It can be used to broadcast events to a subset of clients.

![rooms](https://socket.io/images/rooms.png)

It can be used on the server instead of the client.

https://socket.io/docs/v3/rooms/

**Comment by thucho0103** [comment]
Thanks, I used package in my project <3
