### ISSUE TITLE
Connection is not open

### ISSUE THREAD

**Issue by MrPatryk** [doghappy/socket.io-client-csharp#113]
SocketIOClient.Exceptions.InvalidSocketStateException: Connection is not open.
code:  string json = JsonConvert.SerializeObject(informacje);
             client.EmitAsync("plansza",json );

client is variable created in class, connecting on Form created (it's windows form app), and i recevie data on server that user is connected. After few seconds when user click button he emit "plansza" and nothing happens -nothing for server- because in logs I got connection is not open. Why?

**Comment by doghappy** [comment]
Can you create a reproducible github repository?

**Comment by MrPatryk** [comment]
yes, give me a sec. But can u tell me there is way to storage client for full session of app? Cuz maybe I do something wrong by making global (for class) variable client, then set it by connecting, and in button event click (windows forms) trying emit :# without await

**Comment by doghappy** [comment]
It is correct to use global variables, and you have to await.


```cs
    static class Program
    {
        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            SocketIO = new SocketIO("https://example.com");
            Application.SetHighDpiMode(HighDpiMode.SystemAware);
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new Form1());
        }

        public static SocketIO SocketIO { get; private set; }
    }

    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void Form1_Load(object sender, EventArgs e)
        {
            Program.SocketIO.On("plansza", Plansza);
            await Program.SocketIO.ConnectAsync();
        }

        private void Plansza(SocketIOResponse response)
        {
            Console.WriteLine(response.ToString());
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (Program.SocketIO.Connected)
            {
                Program.SocketIO.EmitAsync("plansza", ...);
            }
            else
            {
                MessageBox.Show("SocketIO is disconnected");
            }
        }
    }
```
