### ISSUE TITLE
Doesn't connect to Socket IO server 3.1.0

### ISSUE THREAD

**Issue by astronaako** [doghappy/socket.io-client-csharp#118]
Cannot connect to NodeJS App running Socket.IO@3.1.0 but works with Socket.IO@3.0.5

**Comment by doghappy** [comment]
I used `Socket.IO@3.1.0` test and it works.

Have you explicitly set EIO?

```cs
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                EIO = 4
            });
```

**Comment by astronaako** [comment]
Ah, that was the issue 😳
Thank you
