### ISSUE TITLE
await client.ConnectAsync() not waiting for connection ? 

### ISSUE THREAD

**Issue by netopierre** [doghappy/socket.io-client-csharp#119]
I'm using your latest version 2.1.3 with a socket.io server 3.1
I'm using the await to connect but it doesn't seem to be waiting for the connexion response (either a Connected status or a connexion error).
Am i wrong supposing it should wait for the connection to either be established or refused ?

Thanks for you great work :)

**Comment by doghappy** [comment]
This library uses websocket to send data.

`await socket.ConnectAsync()` websocket connection has been established

`socket.OnConnected += (s, e) => {... }` socket.io connection is established

**Comment by netopierre** [comment]
Thanks for reply.
Indeed the OnConnected event is working when the connection is established. But the ConnectAsync() is only asking to Connect but is not waiting for the connection to be established.
If I want to wait for the connection to be established when calling ConnectAsync, I need to add some code to wait for OnConnected event.

If I use those 2 lines of code 
await socket.ConnectAsync();
Console.WriteLine(client.Connected);

**Comment by doghappy** [comment]
After the WebSocket connection is established, the server will send some data to the client, which includes PingInterval, PingTimeout, and SocketId. After the client receives these data, it means that the Socket.IO connection is established.

> If I want to wait for the connection to be established when calling ConnectAsync, I need to add some code to wait for OnConnected event.

Yes

> The second line will always show false.

`client.Connected` will be updated when the Socket.IO connection is established

**Comment by netopierre** [comment]
OK thanks for your reply.
I will add code on my side to wait for the OnConnected event.
