### ISSUE TITLE
about server send json string

### ISSUE THREAD

**Issue by 0x2CA** [doghappy/socket.io-client-csharp#12]
my client get error json when i send json in my server,such as:
 send `{"code":200,"msg":"\u8fde\u63a5\u4e0a\u4e86","data":["acewdsfadas"]}`
get `"{\"code\":200,\"msg\":\"\u8fde\u63a5\u4e0a\u4e86\",\"data\":[\"acewdsfadas\"]}"`,
but when I use the js library it's normal.

**Comment by 0x2CA** [comment]
> my client get error json when i send json in my server,such as:
> send `{"code":200,"msg":"\u8fde\u63a5\u4e0a\u4e86","data":["acewdsfadas"]}`
> get `"{\"code\":200,\"msg\":\"\u8fde\u63a5\u4e0a\u4e86\",\"data\":[\"acewdsfadas\"]}"`,
> but when I use the js library it's normal.

**Comment by doghappy** [comment]
@0x2CA Can you show me the code? How do you parse the response data?

**Comment by doghappy** [comment]
Did you get the data from the VS debugging tool? It seems that the data is a string rather than a JSON object. You need to parse it again. Maybe the following code will help you.

你获取的到的数据来自 VS的调试工具吗？ 似乎这些数据是字符串而不是json对象，你需要再次解析，或许以下代码对你有帮助

// Listen server events
client.On("test", res =>
{
    Console.WriteLine(res.Text);
    // Next, you might parse the data in this way.
    // 如果你有模型对应返回的json，可以直接反序列化
    var obj = JsonConvert.DeserializeObject<T>(res.Text);

    // Or, read some fields
    // 如果你指向读取部分数据，可以用这些代码
    var jobj = JObject.Parse(res.Text);
    int code = jobj.Value<int>("code");
    bool hasMore = jobj.Value<string>("msg");
    // ...
});

**Comment by 0x2CA** [comment]
Thank you for your reply,I know why is it .The server is send the entire package for serialization,
```
// pakge
{
    data:"{"code":200,"msg":"连接上了","data":["acewdsfadas"]}"
}
```
when it serialization:
```
// pakge
"{"data":"{\"code\":200,\"msg\":\"连接上了\",\"data\":[\"acewdsfadas\"]}"}"
```

when it parse:
```
// pakge
{
    data:"{\"code\":200,\"msg\":\"连接上了\",\"data\":[\"acewdsfadas\"]}"
}
```
This is the root of the problem

**Comment by 0x2CA** [comment]
i use socket.io in unity,i use JsonUtility to parse.it is can't parse.I'll try JsonConvert tomorrow,After I found out that your library had this problem, I read your code and engine-io protocol and re-implemented it myself. I was already 80% done😂.Thanks for your open source, let me thoroughly understand socket. IO❤

**Comment by 0x2CA** [comment]
[My Library ](https://github.com/0x2CA/socket.io-client-csharp)，Can use server emit callback,server can send json or obj,when server send more args,client use first 😂
