### ISSUE TITLE
Add nuget package with strongname

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#121]
Could be possible to provide a nuget package with strong name?

**Comment by doghappy** [comment]
Strong-named works well for .NET Framework, but on .NET Core, I get an error

```
/opt/hostedtoolcache/dotnet/sdk/5.0.102/Microsoft.Common.CurrentVersion.targets(3241,5): error : PFX signing not supported on .NET Core [/home/vsts/work/1/s/src/SocketIOClient/SocketIOClient.csproj]
```

[For .NET Core, strong-named assemblies do not provide material benefits.](https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named)

Do you have a better way?

**Comment by jlareo** [comment]
I think that if you use SNK signing it should work

**Comment by doghappy** [comment]
Thanks, it works
