### ISSUE TITLE
This requires Node.js ?

### ISSUE THREAD

**Issue by hscanlan** [doghappy/socket.io-client-csharp#122]
Just curious, because it says this is for .NET Standard, but requires Node.js ? Why does it require Node.js?

**Comment by doghappy** [comment]
**nodejs is not required**

If you just use it as a client, you don't need to care about nodejs.

If you want to add new code, during the development phase and the test phase, you will use nodejs to start the service on localhost.

![image](https://user-images.githubusercontent.com/20038914/106994421-b2b7d400-67b7-11eb-8d39-5cfa310c7611.png)
