### ISSUE TITLE
Websocket connection state is aborted

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#123]
By sending a document at some point the connection is detected as aborted inside the method "ListenState" (The ClientWebSocket implementation is being used).

![bug](https://user-images.githubusercontent.com/1730523/107223228-34a53880-6a16-11eb-99e4-b96805bc2dee.PNG)

In my logic I am reading and sending a file in chunks of 65536 bytes to later reconstruct the file on the nodejs server. Sometimes, the process cannot be completed due the aborted connection.

The version of the socket.io server is the 2.1.0.

**Comment by doghappy** [comment]
Have you set `EIO` value? Please remove it

```cs
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "dfasdfasfd" }
                },
                //EIO = 4
            });
```

**Comment by jlareo** [comment]
I didn't use that option

**Comment by jlareo** [comment]
Cannot reproduce the error with latest changes =), I close the ticket.
