### ISSUE TITLE
Error messages aren't handled

### ISSUE THREAD

**Issue by GoryMoon** [doghappy/socket.io-client-csharp#13]
When sending an error in a middleware with socket.io it isn't handled on the client.
The message type is: `44`

An example of a middleware:
```javascript
io.use((socket, next) => {
  if (/*check if authed*/) return next();
  next(new Error('Authentication error'));
}
```

**Comment by doghappy** [comment]
Thank you for your feedback, please check NuGet update (1.0.2.6).

```cs
client.OnError += args =>
{
    // to do
};
```

**Comment by GoryMoon** [comment]
Thanks for the quick fix.
