### ISSUE TITLE
Not work on Windows 7 64 bit

### ISSUE THREAD

**Issue by llg94th** [doghappy/socket.io-client-csharp#133]
I have made and WPF app and have used SocketIO
It work fine on windows 10 and windows 8 but not work on windows 7
No event connected or error after ConnectAsync();

**Comment by doghappy** [comment]
Does the program throw an exception?

**Comment by llg94th** [comment]
> Does the program throw an exception?

Thank for respone! My program did not throw any exeption or error log. I have open the port of socket on Fireware setting on this PC but nothing change :(

**Comment by doghappy** [comment]
I run the Console Application(.NET Framework) on Windows 7 64bit and it works. You can use Fiddler to track the websocket to detect where there is a problem.

**Comment by llg94th** [comment]
I have found the problem:
When i create an new Console App and run on Windows 7 64bit
"The specified value is not valid in the 'ssl protocol type' enumeration"

I have ignore it by this code:
System.Net.ServicePointManager.ServerCertificateValidationCallback =  delegate {return true;}

It work on Windows 8 and 10 but windows 7 can not ignore.

**Comment by llg94th** [comment]
[](https://cdn.discordapp.com/attachments/401183317510193166/831181736935292988/unknown.png)

**Comment by llg94th** [comment]
[https://cdn.discordapp.com/attachments/401183317510193166/831181736935292988/unknown.png](url)

**Comment by doghappy** [comment]
try:

```cs
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "xxxx" }
                },
            });

            if (socket.Socket is WebSocketSharpClient)
            {
                var ws = socket.Socket as WebSocketSharpClient;
                ws.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls;
                ws.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
                {
                    return true;
                };
            }
            else
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
                ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
                {
                    return true;
                };
            }

            ...

            await socket.ConnectAsync();
```

**Comment by llg94th** [comment]
> I reproduced your error and the following code works.
> 
> try:
> 
> ```cs
>             var socket = new SocketIO(uri, new SocketIOOptions
>             {
>                 Query = new Dictionary<string, string>
>                 {
>                     {"token", "xxxx" }
>                 },
>             });
> 
>             if (socket.Socket is WebSocketSharpClient)
>             {
>                 var ws = socket.Socket as WebSocketSharpClient;
>                 ws.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls;
>                 ws.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
>                 {
>                     return true;
>                 };
>             }
>             else
>             {
>                 ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
>                 ServicePointManager.ServerCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
>                 {
>                     return true;
>                 };
>             }
> 
>             ...
> 
>             await socket.ConnectAsync();
> ```

Thank you very much! I have search many way but can not work. Now It's working well by using your code. Thanks
