### ISSUE TITLE
socket On not firing 

### ISSUE THREAD

**Issue by c7nasr** [doghappy/socket.io-client-csharp#135]
![image](https://user-images.githubusercontent.com/42423651/115095480-cdc66300-9f21-11eb-8b8c-6554578ee4dc.png)

This is my code; I'm emitting something from the server and another client, but also, the "on" method is not getting run! Also, it doesn't throw any exceptions!

the debug after connection

![image](https://user-images.githubusercontent.com/42423651/115095581-10883b00-9f22-11eb-802c-42d737d76978.png)

this is a bug? or my code is bad?

**Comment by c7nasr** [comment]
![image](https://user-images.githubusercontent.com/42423651/115095696-7d033a00-9f22-11eb-80de-3a8d63052548.png)

on connected function

**Comment by doghappy** [comment]
Can you show your server code?

The code I use on the server side is as follows:

```js
    socket.on('sync_data', (data) => {
        io.emit("data", data);
    });
```

It works

**Comment by c7nasr** [comment]
> Can you show your server code?
> 
> The code I use on the server-side is as follows:
> 
> ```js
>     socket.on('sync_data', (data) => {
>         io.emit("data", data);
>     });
> ```
> 
> It works

yes, thanks. I realized that problem was from the server. sorry for late replay
