### ISSUE TITLE
Emit with CancellationToken

### ISSUE THREAD

**Issue by DmitryBk** [doghappy/socket.io-client-csharp#136]
Are you going to support CancellationToken in async methods (at least EmitAsync)? It would be very helpful to be able to cancel long async operations.

**Comment by 23W** [comment]
Yep, it would be useful to have a feature of canceling outgoing message, especially for big messages or at slow network connection.

**Comment by doghappy** [comment]
It can be implemented, But it should be noted that: when the environment is `.NET Framework 4.5` and `Windows7/Windows Server 2008 R2`, it will not cancel the task.

| Runtime \ System | Windows 7  | Windows 8 |
| :- | :- | :- |
| .NET Framework 4.5 | ❌ | ✔ |
| .NET Framework 4.6 + | ✔ | ✔ |
| .NET Core / 5 | ✔ | ✔ |

I will continue to test its stability, and it will be released to nuget in the near future

**Comment by DmitryBk** [comment]
Great! It`s enough for me. Thank you.

**Comment by 23W** [comment]
Thanks!
