### ISSUE TITLE
Emit json formatted messages

### ISSUE THREAD

**Issue by 23W** [doghappy/socket.io-client-csharp#138]
Hi @doghappy 
Currently all versions of `EmitAsync` method receive objects as arguments, convert them into JSON stream and sends to the socket.io server.
But there are cases when algorithm of Object->JSON serialization should be controlled by client application:

- Using custom Json serializer settings 
- Using custom Json сonverters
- Using other Json serialization library (not Newtonsoft Json)
- Other application logic where serialization logic is moved to other app part
- and so on...

Can we have new API method `EmitJsonAsync(string eventName, string jsonData, Action<SocketIOResponse> ack = null)` that will send already formatted into json string data? 
Or maybe there is another variant: extend `SocketIOOptions` class by new interface parameter e.g.: `IJsonSerializer` that will be implemented by client app and control JSON serialization?

**Comment by doghappy** [comment]
For various reasons, this library is coupled with JSON serialization (Newtonsoft.Json), and we really need to separate it.

When I have time, I will add ideas here. If you already have a better way to implement it, you are also welcome to submit a PR

**Comment by doghappy** [comment]
# Breaking changes in 2.2.0

SocketIOClient v2.2.0 makes `System.Text.Json` the default JSON serializer. If you'd like to continue to use `Newtonsoft.Json`, add the **SocketIOClient.Newtonsoft.Json** NuGet package and set your **JsonSerializer** to **NewtonsoftJsonSerializer** on your SocketIO instance. System.Text.Json is faster and uses less memory.

### Continue to use Newtonsoft.Json

```cs
var client = new SocketIO("http://localhost:11000/");
client.JsonSerializer = new NewtonsoftJsonSerializer();
```

### Custom JsonSerializerOptions/System.Text.Json

```cs
class MyJsonSerializer : SystemTextJsonSerializer
{
    public MyJsonSerializer(int eio) : base(eio) {}

    public override JsonSerializerOptions CreateOptions()
    {
        var options = new JsonSerializerOption();
        options.PropertyNameCaseInsensitive = true;
        return options;
    }
}

// ...

var client = new SocketIO("http://localhost:11000/");
client.JsonSerializer = new MyJsonSerializer();
```

### Custom JsonSerializerSettings/Newtonsoft.Json

```cs
class MyJsonSerializer : NewtonsoftJsonSerializer
{
    public MyJsonSerializer(int eio) : base(eio) {}

    public override JsonSerializerSettings CreateOptions()
    {
        return new JsonSerializerSettings
        {
            ContractResolver = new global::Newtonsoft.Json.Serialization.DefaultContractResolver
            {
                NamingStrategy = new global::Newtonsoft.Json.Serialization.CamelCaseNamingStrategy()
            },
            Formatting = Formatting.Indented
        };
    }
}

// ...

var client = new SocketIO("http://localhost:11000/");
client.JsonSerializer = new MyJsonSerializer();
```
