### ISSUE TITLE
Add custom header to the HTTP Handshake request

### ISSUE THREAD

**Issue by frco9** [doghappy/socket.io-client-csharp#140]
Is it possible to pass an `extraHeaders` param like the NodeJS library ? This would allow us to pass a Authorization header with a jwt token. 
Currently it seems you only support adding query params to the request but not Headers, although it's not allowed to pass a Bearer as query param by our IdP for security reasons. 

Looking quickly at the code it seems there is a method on the `System.Net.WebSockets.ClientWebSocket` to set custom headers. https://stackoverflow.com/a/24530709 
Do you think it would be possible to add such option in the `SocketIOOptions` ? 

Thanks !

**Comment by doghappy** [comment]
try this?

```cs
            var socket = new SocketIO(...);
            var client = socket.Socket as ClientWebSocket;
            client.Config = options =>
            {
                options.SetRequestHeader("name", "value");
            };
```

**Comment by frco9** [comment]
Yes it works ! Thanks a lot !
