### ISSUE TITLE
No such definition RemoteCertificateValidationCallback

### ISSUE THREAD

**Issue by hmorilak** [doghappy/socket.io-client-csharp#141]
I'm relatively new at using socketio in general so this may be an issue with how I'm trying to use the library however when I try to replicate the SSL & Proxy example from the wiki I get the issue:

_'ClientWebSocketOptions' does not contain a definition for 'RemoteCertificateValidationCallback' and no accessible extension method 'RemoteCertificateValidationCallback' accepting a first argument of type 'ClientWebSocketOptions' could be found (are you missing a using directive or an assembly reference?)_ 

As far as I can tell, .Net Framework and .Net standard are completely updated.

```
var socket = client.Socket as ClientWebSocket;
socket.Config = options =>
{
    options.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
    {
        Console.WriteLine("SslPolicyErrors: " + sslPolicyErrors);
        if (sslPolicyErrors == System.Net.Security.SslPolicyErrors.None)
        {
            return true;
        }
        return true;
    };
	
    // Set Proxy
    options.Proxy = proxy;
};
await client.ConnectAsync();
```

Am I doing something wrong? Any help is appreciated.

**Comment by doghappy** [comment]
Please check the namespace of ClientWebSocket. It is `SocketIOClient.WebSocketClient.ClientWebSocket` instead of `System.Net.WebSockets.ClientWebSocket`

**Comment by doghappy** [comment]
Is your target framework .NET Standard 2.0? It has not yet implemented RemoteCertificateValidationCallback.

You can choose these solutions:
- Change the target framework to: .NET Core/5
- Change the target framework to: .NET Framework
- Upgrade the target framework to: .NET Standard 2.1
