### ISSUE TITLE
Not reading incoming bytes?

### ISSUE THREAD

**Issue by dawalters1** [doghappy/socket.io-client-csharp#142]
Recently started using 2.2.0 with the provided newtonsoft.json example, but seemingly unable to retrieve bytes for placeholders?

The serializer throws an error that the provided index is out of range... This worked fine pre 2.2.0, any suggestions?

Previous solution provided 
https://github.com/doghappy/socket.io-client-csharp/issues/48

**Comment by doghappy** [comment]
I'm very sorry, I didn't write enough test code to cause this error. I will release a new version to NuGet within an hour

**Comment by doghappy** [comment]
https://github.com/doghappy/socket.io-client-csharp/commit/e22982a9f92e8a42e6c00f8ebc59234a52a271d8

upgrade `SocketIOClient.Newtonsoft.Json` to **v2.2.1**

**Comment by dawalters1** [comment]
Sorted Now, Thanks.
