### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by sekulicb** [doghappy/socket.io-client-csharp#143]
Hi. Thanks for the library.

I'm having problems connecting WPF app build on top of .NET 4.7.2 with Node.js server using Sockets 2.3.0 npm package:

The server is hosted on AWS using nginx proxy that AWS is setting up for my client for their load balancer (for https).

All I do is pass the url address while creating SocketIO object. To my understanding that is enough, but every time I try to call ConnectAsync() method I'm getting exception:

exception -> Unable to connect to the remote server
inner exception -> The remote server returned an error: (400) Bad Request.

Can you tell what could be a potential problem?

All the best,
Bane

**Comment by boomdrak** [comment]
This could be a AWS problem, not socket.io-client one

- Are security groups / firewall rules in order?

- Can you telnet into hostname port 80/443 and get a response?

- Does your browser connecto to the host:port?

**Comment by sekulicb** [comment]
Hi @boomdrak 

- Yes, only my home and office setup can reach API, so that is covered and tested
- Yes, we already have REST API that is working, but only the sockets are not
- Yes, it does. We have one public endpoint like a health check for the server where if you send GET request you should get specific greeting message

I also thought that the AWS is the problem, and that we need to configure nginx.config file, by adding location or something like that, but then last night client gave me a small javascript client that he build himself, where if you pass exact same url (like the one I use in WPF project), and when I start it from my office location, it works. It uses socket.io-client npm 2.3.0 as well, and everything works without any additional setup, so it's not AWS. If it was, this javascript client would not work as well. Something is different when using this library and npm package for Node.js...I just can't figure out what is it.

**Comment by sekulicb** [comment]
This is what server returns:

![image](https://user-images.githubusercontent.com/20758693/120227033-b4b31080-c248-11eb-9cb1-5086b0fb9c4f.png)

**Comment by sekulicb** [comment]
Hi. What is exact version of the socket in the example above? What version does the client library (for c#) use?

**Comment by doghappy** [comment]
The server crashed a few days ago, and I have restart it now.

```
"socket.io": "^2.2.0"
```

**Comment by sekulicb** [comment]
@doghappy Okay so it should work if the server uses 2.3.0 right?

It works on the localhost I can confirm that, but the moment we set it up on AWS, I get bad request with code 3. Last night me and the client tried upgrading node.js server from 2.3 to 4.1.2 which I think is the latest version, and still it was not working. We also tried with SocketOptions where I pass for transports : websocket, thinking that it might not ugprade from polling, but it still didn't solve the problem.....I'm just running out of options

**Comment by doghappy** [comment]
Is it possible to deploy a simple server program for me on your AWS?

**app.js**

```js
const http = require('http');
const socket = require('socket.io');
const server = http.createServer();
const port = 11004;
const io = socket(server);
io.on('connection', socket => {
    socket.on('hi', (msg) => {
        socket.emit('hi', msg + new Date().getTime());
    });
});
server.listen(port, () => {
    console.log('listening on *:' + port);
});
```

**package.json**

```
    "scripts": {
        "start": "node app.js"
    },
    "dependencies": {
        "socket.io": "4.1.2"
    }
```

This helps me find problems and fix them faster. I defined the port in app.js, you can change it.

**Comment by sekulicb** [comment]
I can create an AWS account, and add a user for you and then you could deploy?

**Comment by doghappy** [comment]
I am not good at AWS, I can create docker image for you, or install nodejs environment and deploy for you

**Comment by sekulicb** [comment]
Okay no problem, I will deploy to AWS the app.js and then we can test.

**Comment by sekulicb** [comment]
Okay one update: if url looks like this:

https://url/socket.io/.....**transport=polling** then it works, tested with the browser, but the library is sending transport=websocket. Now we already tried on the server to pass just websocket in transports but it didn't changed anything. So looks like the library is not upgrading to websocket. This is 99% the reason why the javascript client works on my machine, since it can negotiate better on initial connection. Is there a way to fix this somehow?

**Comment by doghappy** [comment]
This library does not support polling yet, it only implements websocket.

The default value of socket.io transport is: `["polling", "websocket"]`. If you set the transport value on the server side to `["polling"]`, on the client side (current library), you will get an exception:

```
Unhandled exception. System.Net.WebSockets.WebSocketException (997): The server returned status code '400' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at SocketIOClient.WebSocketClient.ClientWebSocket.ConnectAsync(Uri uri) in D:\repo\socket.io-client-csharp\src\SocketIOClient\WebSocketClient\ClientWebSocket.cs:line 50
   at SocketIOClient.SocketIO.ConnectCoreAsync(Boolean allowedRetryFirstConnection, Action connectBefore) in D:\repo\socket.io-client-csharp\src\SocketIOClient\SocketIO.cs:line 199
   at SocketIOClient.SocketIO.ConnectAsync() in D:\repo\socket.io-client-csharp\src\SocketIOClient\SocketIO.cs:line 158
  ...
```

The following configuration works because it uses default values:

```js
const http = require('http');
const socket = require('socket.io');
const server = http.createServer();
const io = socket(server);
```

The following configuration works because it contains websocket:

```js
const http = require('http');
const socket = require('socket.io');
const server = http.createServer();
const io = socket(server, {
    transports: [
        "polling",
        "websocket"
    ]
});
```

**Comment by sekulicb** [comment]
Hi @doghappy 

As I said, we already tried this, was one of the first things we changed on the server. As you can see from snippet:

![image](https://user-images.githubusercontent.com/20758693/122059162-a1797680-cdec-11eb-9e6a-3d7852dd1b69.png)

But it still wont budge...maybe I need to initialize it the way you have?

**Comment by doghappy** [comment]
What is the implementation of `socketio.listen`?

**Comment by sekulicb** [comment]
This is internal method of the socket.io lib

![image](https://user-images.githubusercontent.com/20758693/122064074-2070ae00-cdf1-11eb-811c-232e48443975.png)

**Comment by sekulicb** [comment]
@doghappy  From the official docs: https://socket.io/docs/v4/server-api/#server-listen-httpServer-options but keep in mind the version is 2.3 not 4.x like in the link, I just could not find for my version.

**Comment by doghappy** [comment]
https://socket.io/docs/v2/client-api/

**Comment by doghappy** [comment]
![test](https://user-images.githubusercontent.com/20038914/122069279-a576ba00-ce27-11eb-98af-16b1e03e19cf.gif)

**Comment by sekulicb** [comment]
The link you send is for client API, listen is for server.

Okay so are you saying that if you just put "websocket" to listen method, without polling it doesn't work? Because It's works locally on my machine. So both options need to be passed into transports?

**Comment by doghappy** [comment]
It has nothing to do with polling. This library only uses websocket, and the server must enable websocket support (in the transport array). But the default transport of socket.io is:

```js
transport:["polling", "websocket"]
```

---

https://socket.io/docs/v2/server-api/#server-listen-httpServer-options

version v4 to v2

**Comment by sekulicb** [comment]
Closing this since the client decided to go with third party service to handle push notifications. Sad thing, but I just could not get it to work, and we need to move on with the project...
