### ISSUE TITLE
OnDisconnected When Fires

### ISSUE THREAD

**Issue by SilentBlueD666** [doghappy/socket.io-client-csharp#147]
This is more of a question?

Is there a design reason why the OnDisconnected is not fired when, SocketIOClient.SocketIO.DisconnectAsync() is called?

**Comment by doghappy** [comment]
Yes, it is designed not to be triggered when you DisconnectAsync()

**Comment by SilentBlueD666** [comment]
Ok thanks for getting back so quick.
