### ISSUE TITLE
How can we send user-agent with connection request headers?

### ISSUE THREAD

**Issue by dotriz** [doghappy/socket.io-client-csharp#148]
I am trying to connect to Socket IO 4 server and its going fine so far. But I didn't see any option to send user-agent along with connection request? Is this any way to do that?

**Comment by doghappy** [comment]
SocketIOClient:

```cs
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                EIO = 4
            });

            var client = socket.Socket as ClientWebSocket;
            client.Config = options =>
            {
                options.SetRequestHeader("User-Agent", "SocketIOClient");
            };
```

socket.io server:

```js
io.on('connection', socket => {
    console.log("userAgent: " + socket.request.headers["user-agent"]);
});
```

**Comment by dotriz** [comment]
@doghappy by using your example, I am getting following error:

> System.ArgumentException: 'The 'User-Agent' header must be modified using the appropriate property or method.
> Parameter name: name'

**Comment by doghappy** [comment]
Works on .NET Core, but not on .NET Framework

https://stackoverflow.com/a/56144252/7771913

https://github.com/dotnet/runtime/issues/24822

Other names can be used, for example: User-Agent-1, but the server needs to change the code to support it

**Comment by dotriz** [comment]
Got it, thanks for the update. This works 👍
