### ISSUE TITLE
OnConnect event not thrown if server does not include comma into response

### ISSUE THREAD

**Issue by buccia85** [doghappy/socket.io-client-csharp#153]
I had to connect to a server recently, and connection callback event did not work. The whole library did not know it was connected.
Sniffing some networking, it happened that this particular server replied to a namespace connection without appending a comma at the end of the message.
For example:
* Client message: `40/namespace,`
* Server response: `40/namespace`

The library did not recognize the answer. I don't know if it is 100% standard or not; JS library works fine without the comma, though.

I solved changing the condition in `Eio3Handler.cs@61`.
I still haven't tested it deeply to confirm that this fix is enough to solve everything.

**Comment by doghappy** [comment]
What version of socket.io are you using

**Comment by buccia85** [comment]
Sorry, I forgot to mention

We are connecting to a third party software, asserting it is using socket.io version `2.0.4`.

What we did was:

1. mock a **server**, using original JS library tagged `2.0.4` on GitHub: the comma was included into the response
2. use the original JS library `2.0.4`, run a **client** against the server we need to use: the server does *not* include the comma, but the JS client handled it successfully (as this library would, with the change suggested before)

The server is using `EIO=3`, obviously, since I mentioned `Eio3Handler.cs`.

I tried to understand if the JS library handles this situation _explicitly_, but my knowledge in JS is very poor, especially when it goes deep into asynchronicity.

Best,
Fulvio

**Comment by doghappy** [comment]
I use the v2.0.4 of socket.io, and there are still commas.

It's really worrying. A long time ago, someone had reported a similar problem.

But I can't reproduce it, can you help me reproduce it

**Comment by buccia85** [comment]
Unfortunately, I can't.

We are using a third party socket.io server, as part of a commercial framework, which his behaving as describing (i.e. replying without the comma).

I think there are 2 possibilities, depending on the standard:
* the comma is not required _by the standard_: you just apply the change I suggested
* the comma is required: it is a server issue, could be none of your business, you decide what to do about your library, considering that JS client supports it

BTW, I am now using a clone of your library, with the mod applied. If it works, it is suitable for me.

I am no JS expert at all, but I think you could easily clone the `2.0.4` socket.io source code, find where that comma is appended, remove it, and you have the chance to replicate the problem

**Comment by doghappy** [comment]
It seems that the namespace does not need to be too strict, as you said, just change `Eio3Handler.cs#61`.

Where did you modify it? Do you have time to create a new pr? Thank u

**Comment by buccia85** [comment]
Did it.
I had to read a tutorial on how to make a PR, so please check that everything is OK :)
On source code side I just changed a single line, so I am just talking about making the PR correctly, choosing the right branch, and stuff like that.
Thanks!
