### ISSUE TITLE
Compatibility with windows 7, windows server 2008 and windows 10

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#155]
Will the library work for both Operating Systems? I saw that there is an implentation specific for Windows 7 and I was wondering if the library is able to identify the current OS and based on that decide which implementation to use.

If is not like that, I would suggest to implement it since many applications will require support for both OS.

Thank you so much

**Comment by jlareo** [comment]
But maybe this change is not needed if the windows 7 implementation is compatible with windows server 2008 and windows 10. Do you know if can be used without problems?

**Comment by doghappy** [comment]
`SocketIOClient.Windows7` uses WebSocketClient in [System.Net.WebSockets.Client.Managed](https://www.nuget.org/packages/System.Net.WebSockets.Client.Managed/)(Assembly: System.Net.WebSockets.Client.Managed.dll)
`SocketIOClient` uses WebSocketClient in System.Net.WebSockets(Assembly: System.Net.WebSockets.Client.dll)

For information about `System.Net.WebSockets.Client.Managed`, please check the [readme](https://github.com/PingmanTools/System.Net.WebSockets.Client.Managed/)

---

If your client will run on Windows7/Windows Server R2, please use `SocketIOClient.Windows7`, it will also work on Windows10.
