### ISSUE TITLE
Add nuget package with strongname for SocketIOClient.Windows7

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#157]
Hi,
Could be possible to add also a strongname for that nuget package? (SNK signing)

Thank you

**Comment by doghappy** [comment]
Thanks for your suggestion, I have added it to the project, waiting for the next release

**Comment by jlareo** [comment]
> Thanks for your suggestion, I have added it to the project, waiting for the next release

When it is planned the release of the new version?

**Comment by doghappy** [comment]
Already published to NuGet

**Comment by jlareo** [comment]
Thank you so much!

**Comment by jlareo** [comment]
I updated the package and seems like by using an strong name with SocketIOClient.Windows7 will not work since System.Net.WebSockets.Client.Managed does not have a strong name. I get an error if I try to use the library. @doghappy

**Comment by doghappy** [comment]
Good idea, can you post a PR?

**Comment by jlareo** [comment]
Sorry I don't have much time this week

**Comment by doghappy** [comment]
It's okay. I'll try tomorrow.

**Comment by doghappy** [comment]
v2.2.4.1 is available in nuget.

[Signing a third-party assembly](https://stackoverflow.com/a/331555/7771913)

**Comment by jlareo** [comment]
I got the following exception:

The file or assembly "System.Net.WebSockets.Client.Managed, Version=1.0.22.0, Culture=neutral, PublicKeyToken=9b40906ee1f14147" or a dependency on it was not found. The assembly manifest definition found does not match the assembly reference. (Exception from HRESULT: 0x80131040).

**Comment by jlareo** [comment]
@doghappy 

Would not be easier to integrate the code System.Net.WebSockets.Client.Managed to the Windows 7 project. (instead of the .dll) to your project? And then just rename the namespace so you will not have any conflict. The System.Net.WebSockets.Client.Managed has a MIT license so should be Ok.

That way should be signed without problems.

**Comment by doghappy** [comment]
I added v2.2.4.1 dependency to a new project, there was no exception

**Comment by jlareo** [comment]
This exception is thrown at runtime, did you try to use the dll?

**Comment by jlareo** [comment]
@doghappy 

I believe System.Net.WebSockets.Client.Managed.dll is not being copied to the build folder. That´s why I get the error that is not found

**Comment by jlareo** [comment]
By making a build of your project, seems like the dlls is copied. Maybe your missing something in the process of building the nuget package?

**Comment by jlareo** [comment]
I saw that the nuget package was deprecated. Will you stop supporting the Windows7 implementation, or it was just deprecated that version because of the error. @doghappy

**Comment by doghappy** [comment]
Sorry, I have been busy and have not dealt with this issue.

I have released v2.2.4.2-alpha.1 to NuGet. It contains a strong named System.Net.WebSockets.Client.Managed

**Comment by jlareo** [comment]
Great, I will test it

**Comment by jlareo** [comment]
@doghappy now is working!, thank so much
