### ISSUE TITLE
Missing dotnet/corefx#29853 fix

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#169]
I realized that the Manage.Websocket library (used in the Windows7 project) is missing the following fix: https://github.com/dotnet/runtime/issues/26240

I found a nuget package that could be used as replacement:

Nuget: https://www.nuget.org/packages/matthid-System.Net.WebSockets.Client.Managed/

GitHub fork: https://github.com/matthid/System.Net.WebSockets.Client.Managed/commits/master

Commit with the fix:
https://github.com/matthid/System.Net.WebSockets.Client.Managed/commit/d1effee32d7dfb81e809f32a5c10e73a51501174
    
(Btw I believe it has a strong name)

Alternative maybe it would be a good idea to make a fork, and create a specific Nuget package

**Comment by doghappy** [comment]
I used "matthid-System.Net.WebSockets.Client.Managed" and removed "lib/System.Net.WebSockets.Client.Managed.dll".

https://github.com/doghappy/socket.io-client-csharp/commit/3fb10f712f807489e13d730224435b285b697925
