### ISSUE TITLE
No way to add custom headers?

### ISSUE THREAD

**Issue by emelin2004** [doghappy/socket.io-client-csharp#170]
Is there a proper way to add custom headers into a handshake request?

**Comment by doghappy** [comment]
https://github.com/doghappy/socket.io-client-csharp/issues/140

**Comment by emelin2004** [comment]
I get this output
`
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0039	Cannot convert type 'SocketIOClient.WebSocketClient.IWebSocketClient' to 'System.Net.WebSockets.ClientWebSocket' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion
`

**Comment by doghappy** [comment]
`var client = socket.Socket as System.Net.WebSockets.ClientWebSocket;`
