### ISSUE TITLE
Remove dependency of Newtonsoft.json with the SocketIO.Client project

### ISSUE THREAD

**Issue by jlareo** [doghappy/socket.io-client-csharp#172]
I think it would be a good idea to remove that dependency by adding a new DLL (for example SocketIO.Core)

The main benefits are:

1) We could create a new test project but that uses the Windows 7 client (eg.  **SocketIOClient.Windows7.Test**, that internally  just have references to the existing tests already implemented in the current test project). Currently it is not possible since the test project depends on the Newtonsoft project and that one on the SocketIOClient project.

2) By having a core DLL could be great if we wanted to have in the future a .net implementation of the socket.io server (but maybe this is thinking too much, at the end is not the scope of this project)

**Comment by doghappy** [comment]
Exactly.

I have modified a lot of SocketIOClient.Windows7:

1. Delete a lot of cs files, they are referenced from "SocketIOClient"
2. Created a new IWebSocketClient implementation

If users want to add support for Windows 7, they can do this:

```cs
var socket = new SocketIO(...);
socket.Socket = new ClientWebSocketManaged();
```

`SocketIOClient.Windows7` just helps users to use `matthid-System.Net.WebSockets.Client.Managed` to implement an `IWebSocketClient`.

Essentially `SocketIOClient` is `Core`.

Do you have anything to improve? Thank you.

**Comment by jlareo** [comment]
If there are no plans to implement also the socket.io server in .net then keep it as it is, otherwise, it would be interesting moving classes that could be shared between the client and the server to a CORE DLL and keep client specific logic inside the SocketIO.Client.
