### ISSUE TITLE
Reconnection after explicit disconnection 

### ISSUE THREAD

**Issue by DmitryBk** [doghappy/socket.io-client-csharp#173]
Hi
Currently, the lib tries to reconnect after explicit disconnection from the server with "io server disconnect". According to the socket.io protocol, the lib should not start reconnection for "io server disconnect" and "io client disconnect" reasons.
Even setting up `Options.Reconnection` to false in `OnDisconnected` event handler doesn`t help, because library starts reconnection before I have received and handled this event.

**Comment by DmitryBk** [comment]
Hi @doghappy 
I`ve created pull-request #175
Please take a look.

**Comment by 23W** [comment]
Hi @doghappy 
I see the same issue on my side. According to [the doc](https://socket.io/docs/v3/client-socket-instance/) if server disconnect session with `reason` equal to "io server disconnect" client should not reconnect so application have to do it manually if needs by calling `ConnectAsync` again.

Please see doc reference for event `disonnect`.
![image](https://user-images.githubusercontent.com/11534020/125826242-4a3a55c0-1942-4e92-a2ae-f0e64fd94282.png)

**Comment by jlareo** [comment]
I made a PR but it is pending to fix some tests

**Comment by 23W** [comment]
@jlareo 
You PR  #177 looks good, can you please add some feature that present in #175. #175 introduces new internal event `OnDisconnectedInternal` that run re-connection logic after propagation `OnDisconnected` event between all library subscribers, so all subscribers will receive `OnDisconnected` event first and `OnReconnecting` event last. It could help subscribers to tune own business logic correctly and cancel reconnection flow if it's required (by setup `client.Options.Reconnection` to `false` inside OnDisconnected` event handler);

**Comment by jlareo** [comment]
Instead of that I would suggest maybe could be possible to have an event called for example: 

OnBeforeReconnect

that could have a boolean as parameter to stop the reconnection.

**Comment by 23W** [comment]
> OnBeforeReconnect

@jlareo 
Yes, agree, it's also good idea. But in any case we need to have guaranty of events firing order: `OnDisconnected` => `OnBeforeReconnect` => `OnReconnecting`.
It should not be possible to get  `OnBeforeReconnect` before `OnDisconnected` for any subscribing scenario.

@doghappy 
do you agree with it?

**Comment by doghappy** [comment]
io server disconnect  
io client disconnect  
> In the first two cases (explicit disconnection), the client will not try to reconnect and you need to manually call socket.connect().

I have fixed it. https://github.com/doghappy/socket.io-client-csharp/commit/08f458776a11c286ec645d29db9a2dbdb2c60c2f

---

> But in any case we need to have a guarantee of events processing order: `OnDisconnected` => `OnBeforeReconnect` => `OnReconnecting`.

In this [commit](https://github.com/doghappy/socket.io-client-csharp/commit/6d79a787f7bca8e31d244415af01017087330c31), I asserted the sequence of events.

When an event occurs, I add the event name to the array, and finally assert their order.

---

I modified the logic of connection and reconnection, so there is no need to add the `OnDisconnectedInternal` event.

---

> I personally don't like the idea of modifying the options object inside the Disconnected event.

me to :) , to do this, from a programming point of view, we only need to do this:

```cs
    public class ReconnectArgs
    {
        public ReconnectedArgs()
        {
            AutoReconnection = true;
        }

        public int Attempts { get; }
        public bool AutoReconnection { get; set; }
    }

...

// public event EventHandler<int> OnReconnectAttempt;
public event EventHandler<ReconnectArgs> OnReconnectAttempt;

...
var args = new ReconnectArgs();
args.Attempts = Attempts;
//OnReconnectAttempt?.Invoke(this, Attempts);
OnReconnectAttempt?.Invoke(this, args);
if (!args.AutoReconnection)
    // to do

...

// subscriber
        private void SocketIO_OnReconnectAttempt(object sender, ReconnectArgs e)
        {
            if (condition)
            {
                e.AutoReconnection = false;
            }
        }
```

---

> help subscribers to tune own business logic correctly and cancel reconnection flow if it's required

In this scenario, can the problem be solved by calling "Dispose()"?

**Comment by 23W** [comment]
@doghappy 
Thank you, are you going to issue a new release (2.2.5) with these fixes?

**Comment by jlareo** [comment]
There are a lot of changes, I would wait a little bit until the tests are finished and we can guarantee that is stable enough
