### ISSUE TITLE
Bug in SocketIOResponse.ToString() method

### ISSUE THREAD

**Issue by 23W** [doghappy/socket.io-client-csharp#178]
Method `SocketIOResponse.ToString()` works incorrectly. On version 2.1.7.0 of the library, it returns a string representation of the received data in json format. In the current version of the library, it keeps returning "_System.Collections.Generic.List`1[System.Text.Json.JsonElement]_".

**Comment by doghappy** [comment]
This is a break change, and I am considering returning this feature.

For now, you can try:

```cs
string json = response.GetValue(index).GetRawText();
```

**Comment by 23W** [comment]
@doghappy 
Thank you, it would be great to have `ToString()` working correctly.

**Comment by doghappy** [comment]
This feature will be included in the next update
