### ISSUE TITLE
IJsonSerializer documentation

### ISSUE THREAD

**Issue by 23W** [doghappy/socket.io-client-csharp#179]
@doghappy 
Hi, can you please add the documentation how to implement interface `IJsonSerializer`, or comments for its methods.
At least it should be commented in code that method Serialize<T>(T data) always gets an array of objects (or enumerable interface of objects). Because currently it's not obvious.

**Comment by doghappy** [comment]
Thanks for your suggestion, I changed the method signature:

```cs
JsonSerializeResult Serialize(object[] data)
```

btw, I implement 2 IJsonSerializer:

- SystemTextJsonSerializer(System.Text.Json) default
- NewtonsoftJsonSerializer(Newtonsoft.Json)

If you use Newtosoft.Json, you can install `SocketIOClient.Newtonsoft.Json` from NuGet

```cs
var client = new SocketIO(...);
client.JsonSerializer = new NewtonsoftJsonSerializer(client.Options.EIO);
```

**Comment by 23W** [comment]
Thank you,
I can not use `NewtonsoftJsonSerializer` because have different logic of serialization in my project that's why I need own implementation of `IJsonSerializer`.
