### ISSUE TITLE
The first OnReconnectAttempt will not trigger when reconnecting

### ISSUE THREAD

**Issue by DmitryBk** [doghappy/socket.io-client-csharp#184]
Hi,
`OnReconnectAttempt` invokes only for the second connection attempt, so it can be a few seconds delay between the client receives `OnDisconnected` and `OnReconnectAttempt` events. It would be helpful if reconnection event is invoked as soon as the reconnection starts.
Pull request #183

**Comment by doghappy** [comment]
If a socket.io server has established connections with many clients, but for some reason, you need to restart the socket.io server. After that, a large number of clients will establish connections with the server at the same time, which may cause the server Crash again.

This is why, by default, the client needs to wait a few seconds (including random factors).

If you need to make the client try to reconnect immediately, you can do this:

```cs
             var socket = new SocketIO(uri, new SocketIOOptions
             {
                 ReconnectionDelay = 0,
                 ReconnectionDelayMax = 0
             });
```

**Comment by DmitryBk** [comment]
Reconnection delay between attempts is good. I meant that the lib currently when starts reconnection doesn`t invoke `OnReconnectAttempt` for the first attempt (`Attempts == 0`), and invokes the event only for the second and next attempts (`Attempts > 0`). It would be very helpful if the lib invokes `OnReconnectAttempt` for the first attempt also. Of course, the event  for the first attempt should be fired only for real reconnection, for initial connection we should not receive `OnReconnectAttempt` with attempt 0.

**Comment by doghappy** [comment]
It seems that after the connection is successful, setting Attemps to 1 can be solved?

https://github.com/doghappy/socket.io-client-csharp/blob/4d1f2c2d9983eb873cf31dadf0e091fef347a0a9/src/SocketIOClient/SocketIO.cs#L515

**Comment by DmitryBk** [comment]
yep, it should fix the issue! Just one note, it seems we should also add `_reconnectionDelay = Options.ReconnectionDelay;` to this place because it will not work in `ConnectAsync` if `Attempts` will start from 1

**Comment by doghappy** [comment]
yeah, at the same time we can delete these codes?

~if (Attempts == 0)~
~{~
~_reconnectionDelay = Options.ReconnectionDelay;~
~}~
~else~ if (Attempts > 0)
{
OnReconnectAttempt?.Invoke(this, Attempts);
}

**Comment by doghappy** [comment]
> yeah, at the same time we can delete these codes?
> 
> ~if (Attempts == 0)~
> ~{~
> ~_reconnectionDelay = Options.ReconnectionDelay;~
> ~}~
> ~else~ if (Attempts > 0)
> {
> OnReconnectAttempt?.Invoke(this, Attempts);
> }

sorry, can't delete it. the first `ConnectAsync()`, we need to get the ReconnectionDelay from the options

**Comment by doghappy** [comment]
Will you modify this pr or create a new pr?

**Comment by DmitryBk** [comment]
sure, I will create a new PR

**Comment by DmitryBk** [comment]
PR #185
