### ISSUE TITLE
OnClosed not working on 1.0.3 and .Net Core

### ISSUE THREAD

**Issue by heliobentes** [doghappy/socket.io-client-csharp#19]
Hi,
I'm using your code on a dotnet core app but I could not make it work on version 1.0.3. When I downgraded it to 1.0.2.7 it worked fine. It can't detect the disconnection event.

Another issue I got was when I emit from the server something without data - like socket.emit("something"). 
It doesn't receive it.

Thanks

**Comment by doghappy** [comment]
I have fixed these issues, please upgrade to 1.0.3.1

**Comment by doghappy** [comment]
The latest NuGet package `1.0.3.3` has been uploaded. Please check for updates.

**Comment by heliobentes** [comment]
Thanks! 1.0.3.3 works like a charm!
