### ISSUE TITLE
'Serialize'  does not have an implementation

### ISSUE THREAD

**Issue by AshotN** [doghappy/socket.io-client-csharp#190]
After upgrading from `2.2.4` to either `2.3.0` or `2.3.1`

I get this error `System.TypeLoadException: 'Method 'Serialize' in type 'SocketIOClient.Newtonsoft.Json.NewtonsoftJsonSerializer' from assembly 'SocketIOClient.Newtonsoft.Json, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'`

from this line

`client.JsonSerializer = new NewtonsoftJsonSerializer(client.Options.EIO);`

I am using EIO version 3 if it matters

My `SocketIOClient.Newtonsoft.Json` version is `2.2.1`

**Comment by jlareo** [comment]
Seems like the Serialize method of SocketIOClient.Newtonsoft was modified but the nuget package was not updated.

@doghappy

**Comment by doghappy** [comment]
https://github.com/doghappy/socket.io-client-csharp/issues/179
