### ISSUE TITLE
Exceptions in ListenAsync are ignored

### ISSUE THREAD

**Issue by gilad-teller** [doghappy/socket.io-client-csharp#193]
If an exception is thrown in ListenAsync, it is ignored.
In my application, I had an issue with System.Text.Json not being loaded.
This caused an exception in OpenedProcessor.Process which was not handled.
The socket was connected, but no messages went through.
#192 In this PR, I added try-catch to ListenAsync, and invoked an OnError event, so the user of the package is informed of the exception.

**Comment by doghappy** [comment]
Thank you for your PR. A better way is to catch exceptions in the SocketIO class, so that you don’t have to change IWebSocketClient.  What do you think? let me know if it works.

**Comment by gilad-teller** [comment]
There is one issue with this fix. Since OpenedHandler is not called, _pingInterval stays 0.
I suggest adding a default value for _pingInterval.
#195
