### ISSUE TITLE
Problem to connect to the https

### ISSUE THREAD

**Issue by sinaone1** [doghappy/socket.io-client-csharp#194]
Hello
I created an example and it works very well in the localhost on my pc but when I test it by our server url it doesn't connect to that.
I created this link for test
[https://tctptest.catalog10.com/](url)
And also I attached server side and client side here
Thank you
[Client Test.zip](https://github.com/doghappy/socket.io-client-csharp/files/7014813/Client.Test.zip)
[Socket-Chat-Server.zip](https://github.com/doghappy/socket.io-client-csharp/files/7014814/Socket-Chat-Server.zip)

**Comment by doghappy** [comment]
It seems that your server websocket is not available, this library only supports websocket, I have planned to add http polling.

> While WebSocket is clearly the best way to establish a bidirectional communication, experience has shown that it is not always possible to establish a WebSocket connection, due to corporate proxies, personal firewall, antivirus software…

https://socket.io/docs/v4/how-it-works/#Transports

**Comment by sinaone1** [comment]
Dear doghappy
I talked to the support team and they told me maybe it's because of keep alive word because it's case sensitive and it must be lower case
![Untitled](https://user-images.githubusercontent.com/11288019/130250997-c306677f-29f3-41f5-8fbf-ef8ede415ef2.png)
Do you think is there any way to change it to be lower case?
Thank you
