### ISSUE TITLE
Client does not hook "on" event

### ISSUE THREAD

**Issue by fob71** [doghappy/socket.io-client-csharp#2]
When I listen an event with:

            // Listen server events
            client.On("ws_message-new", res =>
            {
                Console.WriteLine("WS from server" + res.Text);
            });

It does not work.

Issue (I think) it's related to line 186 in https://github.com/doghappy/socket.io-client-csharp/blob/master/SocketIOClient/SocketIO.cs:
  ...   
  else if (_parserRegex.IsMatch(text))
  ...

I see how message arrives ( in my sample, I receive: "42[\"ws_message-new\",\"message from server\"]" ), but it's not hooked by "on" method.

I use the following versions:
node: v10.16.0
socket.io: 2.2.0
express: 4.17.1

**Comment by doghappy** [comment]
Great issue.

The reason is that the socket.io server URL contains a namespace.

no namespace: http://localhost:3000
namespace is `path`: http://localhost:3000/path

When you Emit, namespace will be added to the request, but your server does not have a corresponding handler

sample server code:

```js
const server = require('http').createServer();
const io = require('socket.io')(server);
const pathNsp = io.of("/path");

io.on('connection', client => {
    client.on('test', data => {
        console.log(data);
        client.emit("test", "test from server");
    });
});

// ...

pathNsp.on('connection', client => {
    client.on('ws_message-new', data => {
        console.log(data);
        client.emit("ws_message-new", "message from server");
    });
});
```

for sample code, work :)

you want emit a event without namespace?

**Comment by doghappy** [comment]
Does your URL contain namespace?

**Comment by doghappy** [comment]
fix :)

https://github.com/doghappy/socket.io-client-csharp/blob/f03a07c1d1c43a32ee3f91d9e49d61264786ce6f/SocketIOClient/SocketIO.cs#L35

**Comment by doghappy** [comment]
@fob71  fix :)

https://github.com/doghappy/socket.io-client-csharp/blob/f03a07c1d1c43a32ee3f91d9e49d61264786ce6f/SocketIOClient/SocketIO.cs#L35

**Comment by fob71** [comment]
it works fine.... thanks a lot
