### ISSUE TITLE
how to use EmitAsync?

### ISSUE THREAD

**Issue by SapiZonk** [doghappy/socket.io-client-csharp#201]
Hi, how to send 2 parameter (id and description) to server in VB.net ?

-------------------------------------------------
 Dim b As Object() = {"id:1", "description:2"}
 Await socket.EmitAsync("create-session", b)
-------------------------------------------------

my server also say undifned
thanks for help

**Comment by doghappy** [comment]
```cs
EmitAsync("create-session", id, description)
```

The server code looks like this:

```js
    socket.on("create-session", (id, description) => {
        console.log(id);
        console.log(description);
    });
```

**Comment by SapiZonk** [comment]
if the server code looks like this:

 socket.on('create-session', function(data) {
    console.log(data.id);
    console.log(data.description);
  });

how to used EmitAsync ?

**Comment by doghappy** [comment]
~Dim b As Object() = {"id:1", "description:2"}~

```vb
        Dim wrongObject As Object() = {"id:1", "description:2"}
        Console.WriteLine(JsonSerializer.Serialize(wrongObject))

        Dim correctObject = New With {Key .id = "123", Key .description = "hello"}
        Console.WriteLine(JsonSerializer.Serialize(correctObject))
```

output:

```
["id:1","description:2"]
{"id":"123","description":"hello"}
```

use correctObject instead of wrongObject.

```cs
Dim b = New With {Key .id = "123", Key .description = "hello"}
Await socket.EmitAsync("create-session", b)
```

**Comment by SapiZonk** [comment]
thanks bro, now it's work
