### ISSUE TITLE
Could not load file or assembly 'System.Text.Json'

### ISSUE THREAD

**Issue by h4k1m0u** [doghappy/socket.io-client-csharp#208]
Hi,

Sorry in advance for the basic question, but is Socketio-client-v3 capable of running on .net Framework 4.8?
I'm constrained of using this version of the SDK instead of .net core as I'm working on a Revit addin, and the latter software doesn't support .net core yet AFAIK.

I'm aware that `System.Text.Json` isn't available on .Net Framework 4.8, and therefore had to use Newtonsoft Json serializer as follows:

```csharp
client = new SocketIO(uri)
    {
        JsonSerializer = new NewtonsoftJsonSerializer(),
    };
```

However doing so shows the following messagebox:

![screenshot](https://user-images.githubusercontent.com/4227512/133784380-3c9d167e-6006-4855-8323-be81028ebbfa.png)

**Comment by doghappy** [comment]
`System.Text.Json` can work on .Net Framework 4.8

Please try to install System.Text.Json for your project

**Comment by h4k1m0u** [comment]
Socketio-client already installed System.Text.Json-v5.0.2 (as a dependency) and I've made a copy of it next to my dlls (just in case). I'll revert to v2.x for now as I'm not yet sure what's behind this issue.

**Comment by h4k1m0u** [comment]
So, I did a test today, I've updated socketio-client to the latest version (3.0.1), and now my Revit addin is complaining that Revit couldn't even find the right version of its assembly with this is error message:

```
Could not load file or assembly 'SocketIOClient, Version=3.0.0.0
```

I checked in my `<project-dir>/packages.config` file and the right version number is mentioned. I'm not sure what it's still looking for that version (3.0.0.0) and not the one installed (3.0.1).

**Comment by h4k1m0u** [comment]
I fixed the issue above by handling assembly loading for `System.Text.Json.dll` separately, I suspect it's Revit who's loading the wrong version of the latter dll. Anyway the code below looks like it solved my problem:

```csharp
Assembly OnResolveAssembly(object sender, ResolveEventArgs args)
{
  string directoryDLLs = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

  // Fix for "Could not load file or assembly 'System.Text.Json" (maybe conflict with Revit)
  if (args.Name.Contains("System.Text.Json"))
  {
    string pathJson = Path.Combine(directoryDLLs, "System.Text.Json.dll");
    return Assembly.LoadFrom(pathJson);
  }

  // other assemblies
  string pathAssembly = Path.Combine(directoryDLLs, args.Name);
  if (File.Exists(pathAssembly))
  {
    return Assembly.LoadFrom(pathAssembly);
  }

  // assembly cannot be resolved
  return null;
}

public Result OnStartup(UIControlledApplication application)
{
  // attach load assembly event handler
  AppDomain currentDomain = AppDomain.CurrentDomain;
  currentDomain.AssemblyResolve += OnResolveAssembly;
```

P.S: I noticed that the last version had more dependencies compared to the one I was using before like System.Runtime.CompilerServices.Unsafe, System.Text.Encoding.Web, System.Threading.Tasks.Extensions, Microsoft.Bcl.AsyncInterfaces.
