### ISSUE TITLE
System.Net.WebSockets.WebSocketException on manual reconnection after manual disconnection

### ISSUE THREAD

**Issue by h4k1m0u** [doghappy/socket.io-client-csharp#215]
During my attempt to have control on when the socketio-client is connected/disconnected to/from server (after setting `Reconnection = false`), I'm getting the following error:

```
System.Net.WebSockets.WebSocketException: 'The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state.'
```

This happens when I:
1) connect
2) disconnect
3) try to reconnect

My code is quite simplistic (and connection/disconnection is triggered by user on button click):

```csharp
Client = new SocketIO(url, new SocketIOOptions
{
    // prevent it from auto-reconnecting (& calling onConnected after disconnection)
    Reconnection = false,
});
await Client.ConnectAsync();

// attach handlers
Client.OnConnected += (object sender, EventArgs e) =>
{
    Trace.WriteLine("Client connecting");
};
Client.OnDisconnected += (object sender, string e) =>
{
    Trace.WriteLine("Client disconnecting");
};
```

Any idea why it fails to reconnect after disconnection?

**Comment by doghappy** [comment]
Fixed, please wait for the next release update

**Comment by h4k1m0u** [comment]
I can confirm it's working for me too, thanks
