### ISSUE TITLE
What is the best way to get this to work in Unity?

### ISSUE THREAD

**Issue by humanfriend22** [doghappy/socket.io-client-csharp#233]
I am working on an app for myself, and I figured I need a WebSocket Unity Client that works with simple Socket.io servers.

After and hour of searching, I decided to post this "issue".

Can someone help me setup this repo with my project?

**Comment by itisnajim** [comment]
check this: https://github.com/itisnajim/SocketIOUnity

**Comment by humanfriend22** [comment]
This is great! Thank you!
