### ISSUE TITLE
Unable to send EmitAsync

### ISSUE THREAD

**Issue by aph5nt** [doghappy/socket.io-client-csharp#24]
Im unable to emit event, as the_namespace is null and i receive an exception

                       var client = new SocketIO("https://socket.stex.com/");
                     
                        client.On("App\\Events\\GlassRowChanged", res =>
                        {
                            Console.WriteLine(res.Text);
                        });
                        
                        client.OnConnected += async () =>
                        {
                            var obj = new
                            {
                                channel = "orderbook_data250",
                                auth = new { }
                            };
                            
                            client.EmitAsync("subscribe", obj).GetAwaiter().GetResult();
                        };
                       
                        client.ConnectAsync().GetAwaiter().GetResult();

**Comment by doghappy** [comment]
Hi, Thanks for your feedback, you can try the latest code.
https://github.com/doghappy/socket.io-client-csharp/pull/25

**Comment by doghappy** [comment]
![image](https://user-images.githubusercontent.com/20038914/76164633-720ca080-618b-11ea-98a4-8bc23e421668.png)

**Comment by doghappy** [comment]
The latest NuGet package `1.0.3.3` has been uploaded. Please check for updates.

**Comment by aph5nt** [comment]
thank you, it's better now... but how do I should parse received data ?
raw text looks like that:
`42["App\\Events\\GlassRowChanged","orderbook_data250",{"currency_pair_id":250,"amount":"5642.21621622","price":"0.00000222","amount2":"0.01252572","count":4,"type":"BUY","socket":null}]`

and text is only ,`"orderbook_data250"`

**Comment by doghappy** [comment]
```cs
client.On("App\\Events\\GlassRowChanged", res =>
{
    // "orderbook_data250"
    Console.WriteLine(res.Text);
}, res =>
{
    // There are two ways to parse data

   // 1
    var jobj = JObject.Parse(res.Text);
    int id = jobj.Value<int>("currency_pair_id");

    // 2
    var data = JsonConvert.DeserializeObject<DataModel>(res.Text);
    
    Console.WriteLine(res.Text);
});

class DataModel
{
    [JsonProperty(“currency_pair_id”)]
    public int CurrencyPairId { get; set; }

    public decimal Amount { get; set; }
}
```

**Comment by doghappy** [comment]
if it still doesn't work, please reopen it.
