### ISSUE TITLE
Invalid state.

### ISSUE THREAD

**Issue by adeelarshad83** [doghappy/socket.io-client-csharp#249]
I am using version 3.0.4 and facing this issue at sometime of the day but not consistent.

Error: System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived' 

How can I check state before sending data

**Comment by doghappy** [comment]
```cs
            if (socket.Connected)
            {
                try
                {
                    await socket.EmitAsync("hi", "test");
                }
                catch (Exception)
                {
                    // retry or other ...
                }
            }
```

**Comment by adeelarshad83** [comment]
Thank you so much
