### ISSUE TITLE
Sample project closes when sending from client to server

### ISSUE THREAD

**Issue by asheroto** [doghappy/socket.io-client-csharp#256]
When running `SocketIOClient.Sample` straight from the current repo, I can receive messages from the server, but if I type anything and hit enter, the program exits with code 0.

```
<program path> (process 11212) exited with code 0.
```

No debugging info for some reason either...

It's Visual Studio 2022 targeting .NET 6. I tried .NET 5 but same issue.

**Comment by doghappy** [comment]
The Sample program does not send user input to the server.

You can find these two lines of code in Main:

```cs
await socket.ConnectAsync();
Console.ReadLine();
```

`Console.ReadLine()` is just to keep the program running, when you hit Enter, the program is done executing, so you get a normal exit code of 0

In `Socket_OnConnected` I use hardcoding to send data to the server.

**Comment by asheroto** [comment]
Ah, I see. How can I keep the program running indefinitely?

**Comment by doghappy** [comment]
After the sample program runs, do not press the Enter key. You can open a new shell window if you want

**Comment by asheroto** [comment]
Thanks
