### ISSUE TITLE
Problem connecting Newtonsoft.Json

### ISSUE THREAD

**Issue by Keeplod** [doghappy/socket.io-client-csharp#268]
var jsonSerializer = new NewtonsoftJsonSerializer();
jsonSerializer.OptionsProvider = () => new JsonSerializerSettings
{
    ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new CamelCaseNamingStrategy()
    }
};
client.JsonSerializer = jsonSerializer;

The compiler cannot find the NewtonsoftJsonSerializer() object, what should I do?(

**Comment by doghappy** [comment]
install `SocketIOClient.Newtonsoft.Json`
