### ISSUE TITLE
OnDisconnect not fired for 'io server disconnect' event

### ISSUE THREAD

**Issue by dawalters1** [doghappy/socket.io-client-csharp#269]
Recently updated to the latest version of this package, and am no longer receiving onDisconnect events for 'io server disconnect' 

![image](https://user-images.githubusercontent.com/28631585/156259921-290af310-619b-42f1-8c67-bda93e423800.png) - Close event was received
![image](https://user-images.githubusercontent.com/28631585/156259894-637d613c-d8ec-42c5-90cc-9c041c2b46d6.png) - Nothing in console
![image](https://user-images.githubusercontent.com/28631585/156259875-17da0a5b-f439-4b81-bc1a-eb22a69852f9.png) - Code is clearly setup to post disconnect

**Comment by doghappy** [comment]
from which version?

**Comment by dawalters1** [comment]
Right after making a mock up V4 server myself, I am in-fact able to detect the 'io server disconnect' event, so I am unsure what is actually happening, the service that I am connecting to has a load balancer that disconnects clients every hour, which is when the issue occurs, and the disconnect is not detected.

https://v3-rc.palringo.com:3051/

**Comment by doghappy** [comment]
Thanks for your service, but I don't know how to connect it, do I need a token or something?

and then: how fired for 'io server disconnect' event

You can send it by mail, thanks. :)

**Comment by dawalters1** [comment]
I guess that information would of been useful to post now wouldn't of it.

I have sent you a code snippet

**Comment by doghappy** [comment]
Sorry, free until now.

I've reproduced it last week, but today when I try to fix it, it seems that the token is not avaliable?

**Comment by dawalters1** [comment]
Nothing has changed as far as i am aware

Would you mind emailing me your code

**Comment by doghappy** [comment]
have you tried with the latest code?

```
Connected To V3 Server
Recieved Packet - welcome
Disconnected From V3 Server -$transport close
Connected To V3 Server
Recieved Packet - welcome
```

that's my logs

**Comment by dawalters1** [comment]
Using the samples project i was also able to get the hourly disconnect as well now 👍🏻
