### ISSUE TITLE
Nuget package for v3.0.6

### ISSUE THREAD

**Issue by theolivenbaum** [doghappy/socket.io-client-csharp#275]
Hi @doghappy,

Quick question, any ideas when the latest release will be pushed to NuGet? 

Thanks!

**Comment by doghappy** [comment]
@theolivenbaum it already published to NuGet

**Comment by theolivenbaum** [comment]
🤦 Sorry about that - VS was being silly with the check for updates, all good!

**Comment by TriStarGod** [comment]
@doghappy Could the ReadMe page be updated with Nuget install command? Just in case someone creates a clone and links back to this project.
