### ISSUE TITLE
Client not responding to hook

### ISSUE THREAD

**Issue by calico-crusade** [doghappy/socket.io-client-csharp#29]
SocketIOClient 1.0.3.3, .net core 3.1, C# 7.2

Summary:
Hooking into an existing service: https://wolflive.com that uses socket.io as their communication back end. SocketIOClient doesn't detect any of the "message send" events, however, a similarly setup javascript version does. I haven't been able to pinpoint the issue, however, I'm fairly certain it isn't something on my end. The example does detect "welcome" events, which is the weird thing.

I'm not sure what version of socket.io the server is on, but the working JS client is 2.3.0. 

here is the C# code:
```CSharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using SocketIOClient;

public class Program
{

	static async Task Main(string[] args)
	{
		string email = args[0], pass = args[1];

		var url = "https://v3.palringo.com:3051";
		var io = new SocketIO(url)
		{
			Parameters = new Dictionary<string, string>
			{
				["device"] = "web",
				["token"] = Token()
			}
		};

		io.On("welcome", async (a) =>
		{
			Console.WriteLine("Welcome Result: " + a.Text);
			await io.EmitAsync("security login", new
			{
				body = new
				{
					username = email,
					password = pass
				}
			}, async (res) =>
			{
				Console.WriteLine("Login Result: " + res.Text);
				await io.EmitAsync("message group subscribe", new
				{
					headers = new
					{
						version = 3
					}
				}, (res) =>
				{
					Console.WriteLine("Msg subscribe: " + res.Text);
				});

				await io.EmitAsync("message private subscribe", null, (res) =>
				{
					Console.WriteLine("Msg DM subscribe: " + res.Text);
				});
			});
		});

		io.On("message send", a =>
		{
			Console.WriteLine("Message: " + a.Text);
		});

		io.OnConnected += () => Console.WriteLine("Connected");
		io.OnClosed += (a) => Console.WriteLine("Closed " + a.ToString());
		io.OnError += (e) => Console.WriteLine("Error " + e.Text);
		//io.OnReceivedEvent += (e, p) => Console.WriteLine("Recieved: " + e + ": " + p.Text);

		await io.ConnectAsync();

		Console.ReadLine();
	}

	private static string Token()
	{
		var Rnd = new Random();
		var d = DateTime.Now.GetTime();
		var uuid = "WExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx".ToCharArray();
		var chars = "abcedf1234567890";

		for (var i = 2; i < uuid.Length; i++)
			uuid[i] = chars[Rnd.Next(0, chars.Length)];

		return string.Join("", uuid);
	}
}
```

Here is the working Javascript version:

```Javascript
<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
</head>
<body>
	<input type="email" id="email" />
	<input type="password" id="password" />

	<button onclick="login()">Login</button>

	<script>
		
		function generateToken() {
			var d = new Date().getTime();
			var uuid = 'WExxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
				var r = (d + Math.random() * 16) % 16 | 0;
				d = Math.floor(d / 16);
				return (c == 'x' ? r : r & 0x3 | 0x8).toString(16);
			});
			return uuid; 
		}
		
		function init(email, pass) {
			//generate the session token
			var token = generateToken();
			//start socket
			var socket = io('https://v3.palringo.com:3051?device=web&token=' + token, {
				transports: ['websocket']
			});
			
			//Hook welcome
			socket.on('welcome', function(data) {
				console.log('welcome result: ', data);
				//send login
				socket.emit('security login', {
					body: {
						username: email,
						password: pass
					}
				}, function(res) {
					console.log('login result: ', res);
					//hook group messages
					socket.emit('message group subscribe', {
						headers: {
							version: 3
						}
					}, function(a) {
						console.log('Message Subscribe: ', a);
					});
					//hook private messages
					socket.emit('message private subscribe', null, function(b) {
						console.log('Message DM Subscribe: ', b);
					});
				});
			});
			
			//Hook messages
			socket.on('message send', function(data) {
				console.log('Message: ', data);
			});
			
			//Hook connected event
			socket.on('connect', function() {
				console.log('connected');
			});
			
			//Hook connection error
			socket.on('connect_error', function(error) {
				console.log('Connection error', error);
			});
		}
		
		function login() {
			var email = document.getElementById('email').value;
			var pass = document.getElementById('password').value;
			
			console.log('starting init');
			init(email, pass);
			console.log("init'd");
		}
		
	</script>
</body>
</html>
```

**Comment by doghappy** [comment]
Passed the test, "message send" can be detected, do you know when "message send" will be emitted by the server?

It seems that `token()` will have different results in the example code you give, **In C# code, the token is not generated using unix time, but the js code uses unix time. Do you get the same token?

**Comment by calico-crusade** [comment]
The "message send" event is triggered whenever someone sends a message in either a group the account is in, or directly to the account. However, the object that is sent to the server using "message send" is different than the one received by the client as the service adds a few more fields and massages the data slightly. 

The return object for the message send event is as follows. I've redacted some sensitive information.
```json
{
  "id": "<guid>",
  "recipient": 0,
  "originator": 1,
  "isGroup": true,
  "timestamp": 1584327403369076,
  "mimeType": "text/image_link",
  "data": {},
  "flightId": "<guid>"
}
```

Data ends up being a complex object in the case of an image, because it sends the file's ID and the file name, in the case of a text/plain it sends as an encoded string, and in the case of rich/html it sends escaped HTML to be used.

The contents of the token doesn't matter. You could put anything there, it is just use to reconnect to the service on a different device once logged in. That C# code is from an earlier revision they had using raw TCP connections, instead of socket.io. The JS code for the token is from their site. Both of them work. 

And as an extra note; I don't own the service, nor do they have any form of developer api or support. However, I did test a .net framework only socket.io-client and it works with the same layout as the one I gave earlier. So it is definitely something weird with this specific client. If needed I can provide the code for the .net framework version as well.

**Comment by doghappy** [comment]
> However, the object that is sent to the server using "message send" is different than the one received by the client as the service adds a few more fields and massages the data slightly.

Yes they are different. The above test code wants to express: "message send" event can be triggered by the server.

Using the code you provided, I just got this. But how do I reproduce it(for web pages)?

![image](https://user-images.githubusercontent.com/20038914/76721785-1b4f2a00-677c-11ea-8180-cf81dd64a6b8.png)

**Comment by calico-crusade** [comment]
1) You will need an account from https://wolflive.com It's free, alternatively, I can provide one as I have one to test this specific issue.
2) You will need to join a group, click the 3rd tab on the left side, click the magnifying glass in the bottom left. And you can search for "src" and join it. 
3) Sending a message in that group will cause the message send even to trigger.

**Comment by doghappy** [comment]
Awesome, Can you send the test account password to my email? hero_wong@outlook.com

**Comment by calico-crusade** [comment]
Sent from holycardboardquest@gmail.com.

**Comment by doghappy** [comment]
Thanks, I already know why

**Comment by doghappy** [comment]
The reason:
When the server sends a buffer, the client will receive two messages.  
1. 451-["message send",{"_placeholder":true,"num":0}]
2. byte array

The server code looks like this:

```js
client.on('message send', data => {
    var buffer = Buffer.from("message send buffer string", "utf-8");
    client.emit("message send", buffer);
});
```

But this library is not implemented yet, A `MessageEventBinaryParser` should be added to the Parsers folder to capture messages starting with "451-", also need to add a condition to read the buffer 

```cs
else if (message.MessageType == WebSocketMessageType.Binary)
```

https://github.com/doghappy/socket.io-client-csharp/blob/526e954a89f3bcf9f83cc2dfbfbd3a3c0fe7dc74/SocketIOClient/SocketIO.cs#L123

I will try

**Comment by doghappy** [comment]
Hi, I have solved it, you can upgrade the NuGet package

https://github.com/doghappy/socket.io-client-csharp/pull/30

```
Install-Package SocketIOClient -Version 1.0.3.5
```

![image](https://user-images.githubusercontent.com/20038914/76734857-c375ea80-679e-11ea-938b-41a54f013338.png)

**Comment by calico-crusade** [comment]
How do I get the contents of "Data"? It just seems to be a _placeholder: true and num: 0.

**Comment by doghappy** [comment]
Wait an hour for me to make the final changes.

**Comment by calico-crusade** [comment]
Ok! Thanks.

**Comment by doghappy** [comment]
Install-Package SocketIOClient -Version 1.0.3.6

**Comment by calico-crusade** [comment]
I have gotten around this by just skipping the first byte in the array. Probably not the best solution, granted, but it should work for what I need. However, I'm running into another issue. After the first message is received, the client stops receiving the message send packet.

**Comment by doghappy** [comment]
It should be another issue, I see what you mean. I'll look at it again in 10 hours with the test account.

**Comment by doghappy** [comment]
Please upgrade to 1.0.3.7

**Comment by calico-crusade** [comment]
Thanks, I have another question tho. How do you SEND a buffer using your library? Whenever I try to upload a buffer, I get a 500 error.

**Comment by doghappy** [comment]
Please upgrade to 1.0.3.8

```cs
await io.EmitAsync("message send", new
{
    body = new
    {
        recipient = 17694003,
        isGroup = true,
        data = Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()),
        mimeType = "text/plain",
        // flightId
    }
});
```

**Comment by calico-crusade** [comment]
Works like a charm! Thanks!

**Comment by jrichardsz** [comment]
I cannot emit a simple string :(

<PackageReference Include="SocketIOClient" Version="3.0.8" />

**Server : Linux + nodejs v16**

```
const express = require('express');
const app = express()
const server = require('http').Server(app)
const io = require('socket.io')(server, { maxHttpBufferSize: 1e7 })

io.on('connection', function (socket) {
  console.log("headers at connection:")
  console.log(socket.handshake.headers)

  socket.on('hi', async function (msg) {
    console.log(">>>>>>>>>>>>>>"+msg.data);
  });

});

server.listen(3000)
console.log("Running on port: " + 3000)
```

**c# Linux netcore 5**

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Threading;
using System.Net;
using System.Net.Sockets;
using SocketIOClient;
using System.Text;

class Program
{
    static async Task Main(string[] args)
    {
        Console.WriteLine("starting Program.cs");
        var client = new SocketIO("http://localhost:3000");   
        client.OnConnected += async (sender, e) =>
        {
            Console.WriteLine("Connected");
            await client.EmitAsync("hi", "im a simple string"); 
            Console.WriteLine("After send");            
        };
        await client.ConnectAsync();
    }
}
```

## Logs

**Client**

`Console.WriteLine("After send"); ` is not printed

![image](https://user-images.githubusercontent.com/3322836/231970783-862c4cc7-20f8-4578-a254-a6b405cc295d.png)

**server**

Only the connected event is received

![image](https://user-images.githubusercontent.com/3322836/231971918-272e0e5b-a62a-4869-8528-2fd2664d8ae5.png)
