### ISSUE TITLE
DisconnectAsync should be able to stop reconnecting 

### ISSUE THREAD

**Issue by dationguyen** [doghappy/socket.io-client-csharp#303]
Hi team,

I was thinking that we should cancel the Token source associated with ConnectAsync to stop it when we want to call disconnect.
In my test case, the app was in offline mode, the socketClient will keep reconnecting and nothing can stop it. In version 3.0.6, i call Dispose to cancel that token source. but on the most recent version, that line of code is gone.
Could u please double check ?

**Comment by doghappy** [comment]
thanks, let me know if you still have this issue in version 3.0.7
