### ISSUE TITLE
The 'Connection' header value 'Upgrade, Upgrade' is invalid.

### ISSUE THREAD

**Issue by asharmaarcadix** [doghappy/socket.io-client-csharp#315]
Hi,

We are having a node.js Server for socket.io and have hosted it to IIS server.

And for client side we are using  SocketIOClient package in .net core 6.0.
as we try to start a connection we face an issue 
"TransportException: Could not connect to 'ws://localhost:8000/socket.io/?EIO=4&transport=websocket'"
"The 'Connection' header value 'Upgrade, Upgrade' is invalid."

![image](https://user-images.githubusercontent.com/121948808/227452913-75d74f53-1f4b-4a15-aa19-26d35f843ba4.png)

![image](https://user-images.githubusercontent.com/121948808/227451686-a12ee313-cc4f-45e2-984b-c45ae786fa54.png)

But when we try to make connection without hosting it to IIS server ( normally in local). It is working fine but after hosting it to IIS Server, we are not able to make connection. 

Here is the image from index.js of server side.
![image](https://user-images.githubusercontent.com/121948808/227452596-510fc42a-fcee-49c3-89d9-0ec486feae48.png)

Can you please guide me to resolve this issue.

**Comment by doghappy** [comment]
thanks for your feedback.

it seems that IIS returned 2 `Connection: Upgrade`

```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Server: Microsoft-IIS/10.0
Connection: Upgrade
Sec-WebSocket-Accept: NFMfylbwIygrHXmqMg4BFjGQITw=
Connection: Upgrade
X-Powered-By: ASP.NET
Date: Fri, 31 Mar 2023 14:58:21 GMT
EndTime: 22:58:21.838
ReceivedBytes: 109
SentBytes: 0


```

I'm still working on it

**Comment by doghappy** [comment]
https://github.com/tjanczuk/iisnode/issues/699
