### ISSUE TITLE
Is there any active socket.io server implementation? 

### ISSUE THREAD

**Issue by qyl27** [doghappy/socket.io-client-csharp#316]
I am looking for a server implementation of socket.io in C#, any plan to write one?

**Comment by doghappy** [comment]
Why do you need the c# version of socket.io server? If you must use C# on the backend, consider using SignalR instead

**Comment by qyl27** [comment]
Oh, yes, you're right, maybe SignalR is a better choice.
Sorry for my reckless questioning.
