### ISSUE TITLE
MsgPack encoding support instead of Json

### ISSUE THREAD

**Issue by useraccessdenied** [doghappy/socket.io-client-csharp#321]
Hi @doghappy,

Socketio's JS client & server implementation has msgpack support for data serialization via custom parser implementation. See [https://socket.io/docs/v4/custom-parser/#the-msgpack-parser](https://socket.io/docs/v4/custom-parser/#the-msgpack-parser) 

Does this client have an option for implementing/extending a custom parser instead of JSON one? I am keen on implementing this if possible.

Regards.

**Comment by doghappy** [comment]
Yeah, you can do if you want. 

I was busy the past few months and will busy the next few months, and I also will take look if I have the time

**Comment by doghappy** [comment]
I know how to implement it. let's wait 😁

**Comment by useraccessdenied** [comment]
> I know how to implement it. let's wait 😁

Sorry, didn't get you. Do you mean to say you have figured out the plan to implement it and will implement it when you find time? If so, I am keen on understanding what will the plan be. Like would it be a pluggable system where we can swap msgpack and json adapters or hard-coded dependency?

At the moment, I am planning to implement it as hard-coded dependency and later iterate it enough to make it pluggable.

**Comment by doghappy** [comment]
the issue should be closed, I have implemented the MessagePack
