### ISSUE TITLE
how to Connect soketIO 2.x

### ISSUE THREAD

**Issue by Princebin** [doghappy/socket.io-client-csharp#329]
how to Connect soketIO 2.x？how setting

**Comment by doghappy** [comment]
```cs
            var options = new SocketIOOptions
            {
                EIO = EngineIO.V3
            };
```

**Comment by Princebin** [comment]
I have a Socket(2.0) address can get  message by postman.
 var options = new SocketIOOptions
            {
                EIO = EngineIO.V3
            };
            socketIO = new SocketIO("ws://dev.terjin.com:47001/", options);
            socketIO.On("info", response =>
            {
                Console.WriteLine(response);
                string text = response.GetValue<string>();
            });
            socketIO.ConnectAsync();
can not get anything
