### ISSUE TITLE
Support emit events concurrently

### ISSUE THREAD

**Issue by SparkRocket** [doghappy/socket.io-client-csharp#338]
For EmitAsync, it uses int type for `_packetId` and  `++_packetId` operation is not thread-safe. 
```
        private async Task EmitAsync(
            string eventName,
            CancellationToken cancellationToken,
            Action<SocketIOResponse> ack,
            params object[] data)
        {
            _ackActionHandlers.Add(++_packetId, ack);
            await EmitForAck(eventName, _packetId, cancellationToken, data).ConfigureAwait(false);
        }
````

Could we support emit events concurrently?
`++_packetId` may be switch to `Interlocked.Increment(_packetId)` , and use `ConcurrentDictionary` for `_ackActionHandlers`

**Comment by doghappy** [comment]
will be fixing next version
