### ISSUE TITLE
OnClosed not invoked in Xamarin.iOS

### ISSUE THREAD

**Issue by sreerajPR** [doghappy/socket.io-client-csharp#34]
I am referencing this package in a Xamarin.Forms project (chatbot application) which targets both Android and iOS. In Android all functionalities are working perfectly. In iOS, everything is working fine except one. After socket connection is successful (OnConnected is invoked and some messages are emitted and received), if I turn off wifi in iOS device to simulate loss of internet connection, OnClosed is not invoked. This gets invoked while running in Android though. Also, "State" has "SocketIOState.Connected" value. I tried with all nuget package versions from 1.0.2.6 to 1.0.3.8 (which is the latest stable version at this moment), since I saw some PRs mentioning OnClosed was fixed.

**Comment by doghappy** [comment]
If version `2.0.0-beta.1` still hasn't fixed it, please turn it on again
