### ISSUE TITLE
MessagePack deserialization ignores key attributes

### ISSUE THREAD

**Issue by derevnjuk** [doghappy/socket.io-client-csharp#341]
The current implementation of the `SocketIOMessagePackSerializer` does not correctly deserialize message data. Specifically, it fails to recognize and map the data to the corresponding fields, even when key attributes are utilized.

**Steps to Reproduce:**

1. Define a MessagePack object, like the MessagePackUserDto class shown below:
```cs
[MessagePackObject]
public class MessagePackUserDto
{
    [Key("username")]
    public string Username { get; set; } = null!;

    [Key("email")]
    public string Email { get; set; } = null!;
}
```
2. Receive a message from the server with data like this:
```json
{"username": "admin", "email": "test@example.com"}
```
3. Attempt to deserialize the received data using the `GetValue<MessagePackUserDto>()` method.

**Actual Behavior:**

Currently, the `GetValue<T>()` method does not properly map the received data to the class. Instead, it results in an instance of class with fields initialized to null, even when the key attributes are used.

**Comment by derevnjuk** [comment]
@doghappy could you release these changes to NuGet?

**Comment by doghappy** [comment]
released, thank for the PR
