### ISSUE TITLE
When use unity not working

### ISSUE THREAD

**Issue by devprog-dev** [doghappy/socket.io-client-csharp#346]
E/Unity: PlatformNotSupportedException: Operation is not supported on this platform.

Maybe text json not working 
```at System.Text.Json.Serialization.JsonConverter`1[T].WriteCore (System.Text.Json.Utf8JsonWriter writer, T& value, System.Text.Json.JsonSerializerOptions options, System.Text.Json.WriteStack& state) [0x00000] in <00000000000000000000000000000000>:0 ```

**Comment by doghappy** [comment]
I'm not sure why you got PlatformNotSupportedException, have you tried to use `SocketIO.Serializer.NewtonsoftJson` instead?

**Comment by devprog-dev** [comment]
I solved, I change newtonsoft.json for unity. Thank you.
