### ISSUE TITLE
Client stops pinging on reconnect

### ISSUE THREAD

**Issue by dewwalters** [doghappy/socket.io-client-csharp#37]
If the client loses internet connection long enough to get the "ClosedByServer" Disconnect event, the client will automatically reconnect after sometime when internet connection is restored, but when it reconnects the client does not ping which leads to a reconnect loop

**Comment by dewwalters** [comment]
![image](https://user-images.githubusercontent.com/28631585/78457095-da10b280-7675-11ea-85a5-db1e16f291ab.png)

**Comment by doghappy** [comment]
Please upgrade to `1.0.3.9`, the following code is an example of reconnection

```cs
client.OnClosed += async reason =>
{
    Console.WriteLine("reason: " + reason.ToString());
    int i = 0;
    while (true)
    {
        var seconds = Math.Pow(2, i);
        await Task.Delay(TimeSpan.FromSeconds(seconds));
        try
        {
            await client.ConnectAsync();
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
        }
        i++;
    }
};
```

**Comment by dewwalters** [comment]
That has appeared to fix it thank you!
