### ISSUE TITLE
Android Unity3D build: Socket IO callbacks are not executed

### ISSUE THREAD

**Issue by brako** [doghappy/socket.io-client-csharp#371]
Hello,

I am using the 3.0.6 version in my Unity3D project and everything is working fine so far. But I wanted to use the latest version 3.1.1.
When I run my app the Unity editor with version 3.1.1, the code is running as expected. But if I compile the same code to an Android application, it is not working at all.

There is no error in the logs, it seems that the callbacks are not called.

I tried to compile SocketIO to .Net 4.8 and netstandard 2, But it doesn't change anything on the issue.

```
using UnityEngine;
using SocketIO.Client;
using SocketIO.Client.Transport;

public class SocketIOTest : MonoBehaviour
{
    private SocketIOClient client;

    async void Start()
    {
        this.client = new SocketIOClient("http://localhost:3000/", new SocketIOOptions
        {
            Reconnection = true,
            Transport = TransportProtocol.WebSocket
        });

        this.client.OnConnected += (sender, e) =>
        {
            Debug.Log("connected");
        };

        this.client.OnDisconnected += (sender, e) =>
        {
            Debug.Log("disconnected");
        };

        this.client.On("message", response =>
        {
            Debug.Log("receive message");
        });

        await this.client.ConnectAsync();
    }
}
```

Any help is appreciated
Thanks

**Comment by doghappy** [comment]
you set `Reconnection = true` that means once connect fail it will retry in background. if you change it to false, you will be seeing the exception.
