### ISSUE TITLE
Buffers often send before the packet leading to disconnects

### ISSUE THREAD

**Issue by dewwalters** [doghappy/socket.io-client-csharp#38]
![image](https://user-images.githubusercontent.com/28631585/78928241-46bcf000-7a6e-11ea-919c-a69fb0af54ec.png)

**Comment by dewwalters** [comment]
My code:

await client.EmitAsync("message send", new{
{
                recipient = 29976610,
                isGroup = false,
                data =Encoding.UTF8.GetBytes("test example message"),
                mimeType = "text/plain",
                sending = true,
                flightId = Guid.NewGuid().ToString().Substring(0, 6)        
},  resp =>{
//handle response
}

**Comment by doghappy** [comment]
How do I reproduce? can you show part of the code?

This is the result i got

![image](https://user-images.githubusercontent.com/20038914/78959480-a32b1880-7b1d-11ea-9222-1d924b2b1859.png)

**Comment by dewwalters** [comment]
await client.EmitAsync("message send",      new {
                recipient = 29976610,
                isGroup = false,
                data = Encoding.UTF8.GetBytes(data.ToString()),
                mimeType = "text/plain",
                sending = true,
                flightId = Guid.NewGuid().ToString().Substring(0, 6)
            }, r => HandleResponse(r, tsk, packet.Command));

 private static void HandleResponse<T>(ResponseArgs args, TaskCompletionSource<T> tsk, string evtString)
        {
            var response = args.Text.To<object>().ReconstructPacket(args.Buffers).To<Response>();

            if ((int)response.Code >= 200 && (int)response.Code <= 299)
                if (typeof(T) == typeof(HttpStatusCode))
                {
                    var code = response.Code;
                    tsk.SetResult(Unsafe.As<HttpStatusCode, T>(ref code));
                }
                else
                    tsk.SetResult(response.Body.ToString().To<T>());
            else
            {
                if (response.Headers != null && response.Headers.ContainsKey("subCode"))
                    tsk.SetException(new WolfError(evtString, response.Code, int.Parse(response.Headers["subCode"])));
                else
                    tsk.SetException(new WolfError(evtString, response.Code));
            }
        }

**Comment by dewwalters** [comment]
I have experienced this issue several times today, I am not sure the exact steps to reproduce it, there are times the events send properly and then it will randomly send out of order

**Comment by doghappy** [comment]
Please upgrade to version `1.0.3.12`

**Comment by dewwalters** [comment]
havent experienced any issues in 6 days, appears fixed, thanks
