### ISSUE TITLE
Help needed in providing proxy config with while connecting to server

### ISSUE THREAD

**Issue by KishanDasani** [doghappy/socket.io-client-csharp#385]
I am using this library with my .net5 C# code to connect to the server. 

Below is the code snippet I'm using for my use case.

```
private SocketIOClient.SocketIO _socketClient;
_socketClient = new SocketIOClient.SocketIO(uri, new SocketIOOptions {
       Path = "/signaling/socket.io"
});
await _socketClient.ConnectAsync();
```

I need to provide proxy with this configuration.

Can anyone please help me with this?

**Comment by doghappy** [comment]
the SocketIOOptions object has a Proxy property. is it?

**Comment by KishanDasani** [comment]
> the SocketIOOptions object has a Proxy property. is it?

It has, but I have no clue how to use it.
Can you please give a small code snippet showing example of how to give Proxy property with SocketIOOptions?

**Comment by KishanDasani** [comment]
Got it resolved.

```
private SocketIOClient.SocketIO _socketClient;
_socketClient = new SocketIOClient.SocketIO(uri, new SocketIOOptions {
       Path = "/signaling/socket.io"
});
_socketClient.Options.Proxy = new WebProxy("<IP>", port);
await _socketClient.ConnectAsync();
```
