### ISSUE TITLE
no data received from node js server "socket.io": "^4.7.0"

### ISSUE THREAD

**Issue by clarksheng** [doghappy/socket.io-client-csharp#388]
hi, just kept hitting walls the whole afternoon with no data (even ping) received back from a node js socket io server. 
the client runs on windows 11/ vs 2022/ .net 6.0 
it does connect and raise onconnect event but then goes all quiet. no data received, no ondisconnect event no error no nothing... 
any suggestion? thanks in advance.

**Comment by josiahmoreno** [comment]
What was solution this?
