### ISSUE TITLE
Does it support UWP

### ISSUE THREAD

**Issue by soorireddy** [doghappy/socket.io-client-csharp#4]

**Comment by doghappy** [comment]
No, it support. I've run it successfully on UWP.

**Comment by doghappy** [comment]
I will check.

**Comment by doghappy** [comment]
got this error mesages?

```
The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))
```

mebay you should try:

```cs
private async void OnMessageReceived(JObject obj)
{
    var msg = obj.ToObject<WtMessage.Message>();
    if (msg.To.Id == Session.Id)
    {
        await Dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
        {
            msg.CompleteMessageFrom();
            Messages.Add(msg);
        });
    }
}
```

[CoreDispatcher.RunAsync()](https://docs.microsoft.com/en-us/uwp/api/windows.ui.core.coredispatcher.runasync)

[Stackoverflow](https://stackoverflow.com/questions/19341591/the-application-called-an-interface-that-was-marshalled-for-a-different-thread)

**Comment by soorireddy** [comment]
I have been using  MVVM light  , seems to be working now , I'm on it , 

DispatcherHelper.CheckBeginInvokeOnUI(
                              () => {
                                  ViewModelLocator.Current.ShellViewModel.ShowMenu = true;
                                  NavigationService.Navigate("windows_native.ViewModels.HomeViewModel");
                              });
