### ISSUE TITLE
Backslashes crashing socket connection

### ISSUE THREAD

**Issue by KimSchneider** [doghappy/socket.io-client-csharp#42]
I use socket.io to send json data via socket. There are combinations of backslashes that let the socket client crash.

This works:

        socket.emit('data', {
            "data": "test\\test"
        });

        socket.emit('data', {
            "data": "\\test"
        });

This data makes the client crash:

        socket.emit('data', {
            "data": "\\"
        });

        socket.emit('data', {
            "data": "test\\"
        });

Once I send a message with a trailing backslash the client spills "Websocket.Client.WebsocketClient|[WEBSOCKET CLIENT] Error while listening to websocket stream, error: 'Index was outside the bounds of the array.'"

Any chance to fix that? :)

**Comment by doghappy** [comment]
Yes, upgrade to version `1.0.3.13`
