### ISSUE TITLE
SocketIO.State is always None

### ISSUE THREAD

**Issue by bpcuong2013** [doghappy/socket.io-client-csharp#43]
After calling ConnectAsync is executed successfully, the State is not updated to Connected. That's the reason Ping/Pong not call. And the result is no message anymore after some seconds.

Below is the code change I made in my local repository, and it works.
![image](https://user-images.githubusercontent.com/5297147/81779062-275a2c80-951e-11ea-9ff3-72e67ea6d356.png)

**Comment by doghappy** [comment]
SocketIO.State is always None, the possible reason is: not connected to the server yet

When the data returned by the server starts with `40`, it indicates that the connection is successfully established.

https://github.com/socketio/socket.io-protocol#packet

Related code:

https://github.com/doghappy/socket.io-client-csharp/blob/8f52984e3e7354d1131461e785ee87f45cf5d5ed/SocketIOClient/SocketIO.cs#L162-L166

https://github.com/doghappy/socket.io-client-csharp/blob/8f52984e3e7354d1131461e785ee87f45cf5d5ed/SocketIOClient/Parsers/ConnectedParser.cs#L5-L18

**Comment by bpcuong2013** [comment]
Our socket URI is http://<ip>:<port>/notification 

When the data returned by the server starts with 40, the ConnectHandler method is not call because ctx.Namespace is '/Notification,'

![image](https://user-images.githubusercontent.com/5297147/81783739-fc73d680-9525-11ea-8542-c12be46c01b9.png)

![image](https://user-images.githubusercontent.com/5297147/81783483-95eeb880-9525-11ea-88b9-d29e5889232d.png)

**Comment by bpcuong2013** [comment]
We also received data that starts with '40/notification', but ConnectHandler is still not called because of missing common character

**Comment by doghappy** [comment]
you got `40/notification` instead of `40/notification,`?

**Comment by bpcuong2013** [comment]
Exactly, I got 40/notification

**Comment by doghappy** [comment]
You can change the code, add `.TrimEnd(",")`

```cs
 class ConnectedParser : Parser 
 { 
     public override void Parse(ParserContext ctx, ResponseMessage resMsg) 
     { 
         if (resMsg.Text == "40" + ctx.Namespace.TrimEnd(",")) 
         { 
             ctx.ConnectHandler(); 
         } 
         else if (Next != null) 
         { 
             Next.Parse(ctx, resMsg); 
         } 
     } 
 } 
```

I need to do some related research

**Comment by bpcuong2013** [comment]
Got it. Thanks for your support!
