### ISSUE TITLE
Capturing events regardless of name

### ISSUE THREAD

**Issue by TehGM** [doghappy/socket.io-client-csharp#45]
Hi,
I am developing a bot library that uses yours for connection. I have a functional requirement that I have a callback capturing all events regardless of their name, to support strongly-typed extensibility and DI.

The latest stable version has OnReceivedEvent, however it doesn't seem to capture binary events. Some of the events I need to capture are binary.

I upgraded to 2.0 alpha hoping it'd resolve the issue, but I see it no longer supports capturing all events at all. I have to register each event name with .On() method. Unfortunately, this would complicate my library code, and could potentially cause some runtime issues.

Is there a possibility to have OnReceivedEvent back, hopefully tweaked to capture all events, including binary ones?

Thank you in advance!

**Comment by doghappy** [comment]
In no more than one day, I will implement OnReceivedEvent

**Comment by doghappy** [comment]
```
Install-Package SocketIOClient -Version 2.0.0-alpha-2
```

@TehGM I've added
