### ISSUE TITLE
Missing Buffers?

### ISSUE THREAD

**Issue by dewwalters** [doghappy/socket.io-client-csharp#48]
![image](https://user-images.githubusercontent.com/28631585/82128348-773c2c00-9788-11ea-9647-9268d1c13535.png)

On the previous version this information was provided in Buffers, How do i retrieve this information in 2.0?

**Comment by doghappy** [comment]
You can get it this way.

```cs
class MessageSendResponse
{
    public string Command { get; set; }
    public MessageSendBodyResponse Body { get; set; }

class MessageSendBodyResponse
{
    public int Code { get; set; }
    ...
    public byte[] Data { get; set; }
}

client.On("message send", response =>
{
    var res = response.GetValue<MessageSendResponse>();
    // Encoding.UTF8.GetString(res.Data);
})
```

**Comment by dewwalters** [comment]
Alright, now how to do this with OnReceivedEvent?

I get a serialization error because the IncomingBytes contains no items

**Comment by doghappy** [comment]
Can you show me the Exceptions? Thank

**Comment by doghappy** [comment]
Thank you for your feedback

```
Install-Package SocketIOClient -Version 2.0.0-beta.1
```
