### ISSUE TITLE
transports?

### ISSUE THREAD

**Issue by megadrazz** [doghappy/socket.io-client-csharp#49]
not connectivity without transport error !!
to put into production, you don't even get a response from socketio server online !!!! localhost ok! not online production ?????

**Comment by doghappy** [comment]
Which version do you use?

**Comment by megadrazz** [comment]
v2.0.0

**Comment by doghappy** [comment]
![image](https://user-images.githubusercontent.com/20038914/82133215-d4cd8880-981b-11ea-818a-d03080b5a935.png)

`2.0.0-alpha-2` or `2.0.0-alpha`?

**Comment by megadrazz** [comment]
2.0.0-alpha

**Comment by doghappy** [comment]
Please upgrade to the latest version.

I'm not sure if you need to change "path". [https://socket.io/docs/client-api#With-custom-path](https://socket.io/docs/client-api#With-custom-path)

**Comment by megadrazz** [comment]
add transport polling option || websocket

**Comment by doghappy** [comment]
The current version only supports websocket, not polling. Support for polling may be added in the future.

**Comment by megadrazz** [comment]
on the server is defined as transports: ['websocket'] this is not the default ???

**Comment by megadrazz** [comment]
socketio is behind https cloudflare and defined as transports: ['polling'] do you have a suggestion ???

**Comment by doghappy** [comment]
![image](https://user-images.githubusercontent.com/20038914/82133400-355dc500-981e-11ea-8910-5a84b1ac286c.png)

Support websocket if possible?

**Comment by megadrazz** [comment]
WebSocket connection to........
failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by megadrazz** [comment]
if I connect without tranport I get this error
when you connect your api I don't get a response

**Comment by megadrazz** [comment]
sorry for the comfort, looking for a solution!
