### ISSUE TITLE
The WebSocket protocol is not supported on this platform.

### ISSUE THREAD

**Issue by adeiry** [doghappy/socket.io-client-csharp#50]
Could you please help me solve this problem.

I disabled the webSocket in App.config
```
<configuration>
  <system.webServer>
    <webSocket enabled="false" />
  </system.webServer>
</configuration>
```

but still not working. any ideas??

**Comment by doghappy** [comment]
Are you running on windows 7?

**Comment by adeiry** [comment]
yes

**Comment by adeiry** [comment]
@doghappy yes

**Comment by doghappy** [comment]
try install `System.Net.WebSockets.Client.Managed`

**Comment by adeiry** [comment]
@doghappy I installed them still not working!

**Comment by doghappy** [comment]
OK, I'll install the windows 7 VM later

**Comment by doghappy** [comment]
This issue has been fixed in the latest version `2.0.0`. If it has not been fixed, please reopen it.

**Comment by swuttich** [comment]
@doghappy we use version 2.0.1 and get the error on Windows 7. It is not fully clear what are the prerequistes to do to make it work. Is there some configuration required?

**Comment by doghappy** [comment]
I created a new project for Windows 7, and you can pull the code. Add an existing project in VS and reference it.

https://github.com/doghappy/socket.io-client-csharp/tree/windows7/src/SocketIOClient.Windows7

project name: SocketIOClient.Windows7

This is only a temporary plan, I will post to NuGet in the future

**Comment by doghappy** [comment]
If your TargetFramework is `.NET Framework` and it runs on `Windows7/Windows Server 2008 R2`, please install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient.NetFx-%23004880)](https://www.nuget.org/packages/SocketIOClient.NetFx)

Otherwise, we recommend you to install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient-%23004880)](https://www.nuget.org/packages/SocketIOClient)

**Comment by swuttich** [comment]
Thanks @doghappy!

Are you aware of any drawbacks of the NetFx variant compared to the default .NET socket implementation? Or would it be better to have the default SocketIOClient on newer Windows (e.g. Win10)?
