### ISSUE TITLE
Is there a sample to access to server with SSL

### ISSUE THREAD

**Issue by bpcuong2013** [doghappy/socket.io-client-csharp#51]
I need a sample to make access to the server with SSL. Please help. Thanks!

**Comment by doghappy** [comment]
Use a secure URL for your initial connection, i.e. instead of "http://" use "https://".

**Comment by bpcuong2013** [comment]
But no way to import a certificate. The remote certificate is invalid according to the validation procedure.

System.Net.WebSockets.WebSocketException (0x80004005): Unable to connect to the remote server
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.

**Comment by doghappy** [comment]
Can you show me the server options?

Looks like this:

```js
import * as https from "https";
// ...
const server = https.createServer({
    key: fs.readFileSync("cert/server-key.pem").toString(),
    cert: fs.readFileSync("cert/server-crt.pem").toString(),
    ca: fs.readFileSync("cert/ca-crt.pem").toString(),
    requestCert: true,
    rejectUnauthorized: true
});
```

The above code is the test I did, can you show your server?

**Comment by craftbyte** [comment]
I am having same issues. Problem probably arrives since I am doing HTTPS termination on nginx and not node. Any idea why that would be happening?

**Comment by bpcuong2013** [comment]
Sorry, I have no control on the server side.

**Comment by doghappy** [comment]
Refer to https://github.com/doghappy/socket.io-client-csharp/issues/68#issuecomment-662213411 , we can try to do this?

```cs
socket.Options.ClientCertificates.Add(cert);
```
