### ISSUE TITLE
Allow us to set JsonSerializerSettings

### ISSUE THREAD

**Issue by dewwalters** [doghappy/socket.io-client-csharp#52]
![image](https://user-images.githubusercontent.com/28631585/83143898-a2941480-a0c0-11ea-8e55-0139e7f119b1.png)

I am working on developing a bot api for an app that tends to use a lot of nulls which is a headache to change all the classes at this point..., and I typically just ignore nulls with jsonserializersettings but now in V2, there is no way to ignore them, could you please add a way for me to set these settings?

**Comment by doghappy** [comment]
There are two ways for you to choose:

1. Configure global serialization settings, 

```cs
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore
};
```

2. JsonPropertyAttribute

```cs
class TestItem
{
    [JsonProperty("name", NullValueHandling=NullValueHandling.Ignore)]
    public string Name { get; set; }

    public int Age { get; set; }
}

await socket.EmitAsync("hi", new TestItem { Age = 12 });
```

**Comment by dewwalters** [comment]
Guh what a headache
