### ISSUE TITLE
Callback in on()

### ISSUE THREAD

**Issue by rostwolke** [doghappy/socket.io-client-csharp#53]
Is there a way to call a callback function when the client receives a message?

For example in Javascript I can do the following:
```
socket.on('test', function (msg, cb) {
     cb('I received test');
}
```

Thanks in advance.

**Comment by doghappy** [comment]
See README.md Ack

**Comment by rostwolke** [comment]
In that example only the server uses on() with callback function. I am looking for that function on client side.

**Comment by doghappy** [comment]
Thanks for your feedback:
https://github.com/doghappy/socket.io-client-csharp/pull/54

**Comment by rostwolke** [comment]
Looks great, thanks so much! I will directly try it

**Comment by doghappy** [comment]
```
Install-Package SocketIOClient -Version 2.0.1-alpha.1
```

**Comment by rostwolke** [comment]
Short update: worked perfectly.
