### ISSUE TITLE
onDisconnected is never called

### ISSUE THREAD

**Issue by rostwolke** [doghappy/socket.io-client-csharp#55]
I have the problem that the OnDisconnected event is never called. Here my example code:

Client constructor:
```
this._socket.OnConnected += this.Socket_OnConnected;
this._socket.OnDisonnected += this.Socket_OnDisonnected;
```

Client Socket_OnDisconnect:
```
private void Socket_OnDisconnected(object sender, string e) {
     Logger.Log(LogLevel.Trace, "SocketIO Disconnect: " + e);
}
```

The OnConnected event is called but when I restart the socket server (Node.js) the OnDisconnect event is never called. Current version is 2.0.1-alpha.1.

Thanks in advance.

**Comment by doghappy** [comment]
```
Install-Package SocketIOClient -Version 2.0.1-alpha.2
```

**Comment by rostwolke** [comment]
Worked perfectly. Great work!

**Comment by timpulsive** [comment]
Having this problem with 2.1.0. OnConnected works but OnDisconnected is never called when I kill the connection or the server.

Thanks
