### ISSUE TITLE
Disconnect Being fired more than 1 time

### ISSUE THREAD

**Issue by dewwalters** [doghappy/socket.io-client-csharp#56]
When a server tells the client to close, it causes 2 OnDisconnected events to be called, causing the client reconnect twice

![image](https://user-images.githubusercontent.com/28631585/83328708-05b5b080-a253-11ea-85e2-b8812134bf77.png)

![image](https://user-images.githubusercontent.com/28631585/83328746-575e3b00-a253-11ea-8bb6-abad9cfdf9e0.png)

![image](https://user-images.githubusercontent.com/28631585/83328760-74930980-a253-11ea-9087-1dd6f6c93b52.png)

using 2.0.1 alpha.2

**Comment by dewwalters** [comment]
If the client loses internet connection, it only fires once

**Comment by doghappy** [comment]
Which version?

**Comment by doghappy** [comment]
```
Install-Package SocketIOClient -Version 2.0.1-alpha.3
```

**Comment by dewwalters** [comment]
That has solved it thank you...

Another issue i have spotted, is when the client reconnects it stops sending TEXT 2 which is also causing disconnects

Initial first connection: 
![image](https://user-images.githubusercontent.com/28631585/83330043-c25f4000-a25a-11ea-9ee2-edb9394ae057.png)

After reconnect: 
![image](https://user-images.githubusercontent.com/28631585/83330074-e458c280-a25a-11ea-8be7-37a7cdb543ed.png)

**Comment by doghappy** [comment]
Thank you very much for your feedback. ❤👍

```
Install-Package SocketIOClient -Version 2.0.1-alpha.4
```

**Comment by dewwalters** [comment]
Alright, not sure whats going on, was working, now its not, when the server tells the client to close ondisconnect no longer fires

**Comment by dewwalters** [comment]
![image](https://user-images.githubusercontent.com/28631585/83339442-ce1f2680-a29b-11ea-99d3-38f01fe9acd1.png)

**Comment by doghappy** [comment]
Maybe I have fixed it, but I don't know how to reproduce it. If anyone knows how to reproduce, please leave a comment, thanks.

commit: 

https://github.com/doghappy/socket.io-client-csharp/commit/189e003913e802330be228034c31922d70d32a9e

```
Install-Package SocketIOClient -Version 2.0.1-alpha.5
```

**Comment by dewwalters** [comment]
Appears to be working perfectly now, thanks
