### ISSUE TITLE
Ping Timeout on iOS device

### ISSUE THREAD

**Issue by farshid1** [doghappy/socket.io-client-csharp#57]
Hi HeroWong,

Thank you for this great library! 

We are working on a unity project that connects to a socket.io server (v2.3.0). The project runs fine in Unity simulator but when built to an iOS device, the connection is never made and the client is disconnected because of "ping timeout" OR "transport close" reasons.

We were wondering if you have any insight on what could be causing the issue.

**Comment by doghappy** [comment]
Are you using the latest version 2.0.1?

**Comment by farshid1** [comment]
yes

**Comment by doghappy** [comment]
You can use Fiddler to monitor ws traffic to see the difference between Unity simulator and iOS device.

I don't have a Unity or Xamarin environment. 

Are you familiar with how to use Fiddler to monitor ws traffic to PCs and mobile devices?

**Comment by farshid1** [comment]
Thanks for quick response. No we do not but we can certainly learn. What should we be looking for? Differences in server's response?

**Comment by doghappy** [comment]
Step 1: open Fiddler, PC's http and ws requests are recorded to the left
Step 2: Open the program running on the emulator, and after you trigger the connection request, you can find the request in Fiddler https://blog.theknightsofunity.com/debugging-web-services-with-fiddler/
Step 3: Double-click ws type records in fiddler, you can see the data transmitted by ws
Step 4: [Monitor your ios device traffic with fiddler](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS)

**Comment by croced** [comment]
@farshid1 Hey, sorry to reopen this but did you ever find a solution for this? I'm currently running into the same issue - I can establish a connection within the Unity editor but when I build for iOS I can't. It seems to hang on the `socket.connect()` function and eventually times out without ever connecting. Any help would be appreciated - thanks!

**Comment by VanIseghemThomas** [comment]
Same problem, is there a solution to this?
