### ISSUE TITLE
.Net Framework support

### ISSUE THREAD

**Issue by mathrb** [doghappy/socket.io-client-csharp#61]
Hello,

First, thanks for your work. 

The project is currently only available for .NETStandard2.0. I'd like to have a version ready in NuGet that supports .net framework 4 and upper versions.
I did a little experiment, and it appears that your project could easily support it since everything works if we omit the WebSocketClient implementation.
How would you like to proceed? Create a new csproj that links to every files of SocketIOClient project but WebSocketClient.cs ?

I could create a pull request afterwards

Kind regards

**Comment by doghappy** [comment]
Good idea, there is only one problem that needs to be solved: **how to use WebSocket client on .Net Fx 4+**?

The current project uses `System.Net.Websockets.Client.dll` as the ws client, which supports `.NET Standard 1.3+ (.NET Fx 4.6+)`. Therefore, we only need to find alternatives and implement the `IWebSocketClient` interface.

It's worth noting that we don't install `System.Net.Websocket.Client` from NuGet, we can also import the namespace, but it belongs to `System.dll`, running on Windows 7, will throw a PlatformNotSupportedException

> [Some of the classes and class elements in the System.Net.WebSockets namespace are supported on Windows 7, Windows Vista SP2, and Windows Server 2008. However, the only public implementations of client and server WebSockets are supported on Windows 8 and Windows Server 2012. The class elements in the System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are abstract class elements. This allows an application developer to inherit and extend these abstract class classes and class elements with an actual implementation of client WebSockets.](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netcore-3.1)

**Comment by doghappy** [comment]
I tried it and it seems difficult to support .NET Fx 4.5.2 and below, The following implementation is missing:
- Task.CompletedTask
- Task.Delay()

Different delegate signatures:

.NET Framework 4.0:

```cs
public delegate void EventHandler<TEventArgs>(object sender, TEventArgs e) where TEventArgs : EventArgs;
```

.NET Standard 2.0:

```cs
public delegate void EventHandler<TEventArgs>(object sender, TEventArgs e);
```

This may have to change the code of the `SocketIO.cs`

**Comment by mathrb** [comment]
I agree that it does not work with .NET Framework 4.0, but it works like a charm on .NET Framework 4.5 (Currently I've tested win 10 only)

**Comment by mathrb** [comment]
NuGet does not provide a way to target a specific OS version.
I think providing a .Net Fx 4.5+ can still benefit people. Even websocket-sharp does not support windows 7 (https://github.com/sta/websocket-sharp/issues/572). This would require a proper documentation.

**Comment by doghappy** [comment]
https://github.com/doghappy/socket.io-client-csharp/tree/feat-netfx4.5

In this branch, I added some code that may be useful to you

**Comment by mathrb** [comment]
Works fine on my side. Though it would require a -pre release since websocketsharp version is 1.0.3-rc11

**Comment by mathrb** [comment]
How could I help accelerate the publication to NuGet?

**Comment by doghappy** [comment]
Install-Package SocketIOClient.NetFx -Version 1.0.0-alpha3

**Comment by mathrb** [comment]
Hello,

Made a few test with the NetFx version. I'm concerned about reconnexion with Websocketsharp. I doesn't work as expected. Using the [ClientWebSocket ](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket?view=netframework-4.5)of the framework, it works correctly.

**Comment by doghappy** [comment]
If your TargetFramework is `.NET Framework` and it runs on `Windows7/Windows Server 2008 R2`, please install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient.NetFx-%23004880)](https://www.nuget.org/packages/SocketIOClient.NetFx)

Otherwise, we recommend you to install [![NuGet](https://img.shields.io/badge/NuGet-SocketIOClient-%23004880)](https://www.nuget.org/packages/SocketIOClient)
