### ISSUE TITLE
SocketIO.Connected is sometimes false right after "await SocketIO.ConnectAsync()"

### ISSUE THREAD

**Issue by jmegner** [doghappy/socket.io-client-csharp#62]
If I have code like the following...
```
var io = new SocketIO(someOrigin);
io.OnConnected += (s, e) => { Console.WriteLine($"connected event, io.Connected={io.Connected}"); };

Console.WriteLine($"before ConnectAsync, io.Connected={io.Connected}");
await io.ConnectAsync();
Console.WriteLine($"after ConnectAsync, io.Connected={io.Connected}");
```

Then I will often get the following output...
```
before ConnectAsync, io.Connected=false
after ConnectAsync, io.Connected=false
connected event, io.Connected=true
```

Notice the io.Connected being false for the second output line even though we awaited for the completion of ConnectAsync, and we get confirmation that a connection did happen via the OnConnected event.

**Comment by doghappy** [comment]
```cs
io.OnConnected += (sender, e) => Console.WriteLine("Event: " + client.Connected); //true
Console.WriteLine("Before: " + socket.Connected); //false
await socket.ConnectAsync();
Console.WriteLine("After: "+socket.Connected); //false
```

After you called `io.ConnectAsync()`, the websocket connection is completed(socket.io connection is not complete), after which some data will be exchanged, such as `pingInterval` and `namespace`, etc. finally, socket.io connects successfully

**Comment by jmegner** [comment]
Thank you for your prompt and informative response.  Then what is the best way to see if a SocketIO.ConnectAsync was successful?  I was hoping awaiting ConnectAsync then checking IsConnected would do that.

**Comment by doghappy** [comment]
```cs
static async Task Main(string[] args)
{
    var io = new SocketIO(someOrigin);
    io.OnConnected += IO_OnConnected;
}


private static void Socket_OnConnected(object sender, EventArgs e)
{
    // SocketIO.ConnectAsync was successful
    var io = sender as SocketIO;
    io.EmityAsync("hi", "abc");
}
```

**Comment by jmegner** [comment]
What if I wanted code inside Main to learn whether the connection succeeded or failed?

**Comment by jmegner** [comment]
> What if I wanted code inside Main to learn whether the connection succeeded or failed?

I ask that because I am consuming a web service that does a REST API for data and socket.io for notifications of data changes.  I want to have a TestConnection function where I make sure I can connect to both the REST side and the socket.io side, and if I can't, I tell the user what the problem is so they can fix it immediately (like try another credential).  So far, the function is a bit like this...

```
async Task<ConnectionStatus> TestConnections()
{
    var connectionStatus = await _rest.TestConnection();
    if(connectionStatus.IsOk())
    {
        await _io.ConnectAsync();
        if(!_io.Connected)
        {
            connectionStatus = ConnectionStatus.SocketIoIssue;
        }
    }
    return connectionStatus;
}
```

So, how do I get TestConnections to learn whether the _io.ConnectAsync succeeded?  I'd rather not have to attach to the OnConnected event and make sure that it fires within some arbitrary time span after the completion of await _io.ConnectAsync().

**Comment by doghappy** [comment]
You can try this ugly code:

```cs
async Task<ConnectionStatus> TestConnections()
{
    var connectionStatus = await _rest.TestConnection();
    if(connectionStatus.IsOk())
    {
        await _io.ConnectAsync();
        for(int i =0; i < 30; i++)
        {
            if(_io.Connected)
            {
                connectionStatus = ConnectionStatus.SocketIoIssue;
                break;
            }
            else
            {
                await Task.Delay(200);
            }
        }
        if(!_io.Connected)
        {
            connectionStatus = ConnectionStatus.SocketIoIssue;
        }
    }
    return connectionStatus;
}
```

**Comment by jmegner** [comment]
Would you be open to pull requests that implement a function similar to ConnectAsync except the returned tasks completes upon the socket.io connection being complete (rather than the WebSocket connection)?
