### ISSUE TITLE
Add Header To Request

### ISSUE THREAD

**Issue by MohamedMostafa0** [doghappy/socket.io-client-csharp#65]
Thanks for This Library and it is really awesome and everything working correctly but i want to add a header to my request (emit) because i want to implement jwt auth token with my request to a specific function.
So is there is a way to add a header when i'm calling a function or not.
Thank You.

**Comment by doghappy** [comment]
Did you try:

```cs
            var socket = new SocketIO(uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "abcde123123" }
                }
            });
```

**Comment by MohamedMostafa0** [comment]
Thank you it works correctly.

**Comment by beiguancyc** [comment]
> Did you try:
> 
> ```cs
>             var socket = new SocketIO(uri, new SocketIOOptions
>             {
>                 Query = new Dictionary<string, string>
>                 {
>                     {"token", "abcde123123" }
>                 }
>             });
> ```

socket.io V4 has “ auth”, [https://socket.io/docs/v4/client-initialization/#auth]()
I think client should  support for that.
