### ISSUE TITLE
How to use Emit with callback?

### ISSUE THREAD

**Issue by lzd6696** [doghappy/socket.io-client-csharp#66]
Hi all  : 
I am your SocketIoClient User, 
I  follow your github test project and white some  client/ server test case for testing .

Server: I add a server event in your socket.io-server.njsproj as follows:

```
    socket.on("v1/chat/enter", (msg2) => {
        console.log("v1");
        console.log(`${msg2.toString()}`);
        const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
        socket.emit("v1/chat/enter", binaryMessage2);
    });
```

then I Add 2 Client Test Case:

Client Case 1:

```
     private readonly EventWaitHandle _waitsocketioconnected2 =
            new AutoResetEvent(false);
        [TestMethod]
        public async Task LocalEnterChatRoomTest3()
        {
            var client = new SocketIO(Uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "io"}
                },
                ConnectionTimeout = TimeSpan.FromSeconds(10)
            });

            client.OnConnected += async (sender, e) => { _waitsocketioconnected2.Set(); };

            Stopwatch watch;

            _waitsocketioconnected.Reset();
            await client.ConnectAsync();

            _waitsocketioconnected.WaitOne(10000);

            Action<SocketIOResponse> reponseaction = async delegate(SocketIOResponse ack)
            {
                Trace.WriteLine("v1/chat/enter Ack.");
                await ack.CallbackAsync();
            };

            string Test = "DemoString";
            client.On("v1/chat/enter", reponseaction);

            await client.EmitAsync("v1/chat/enter", Encoding.UTF8.GetBytes(Test));
            //await client.EmitAsync("v1/chat/enter", reponseaction,Encoding.UTF8.GetBytes(Test));

        }
```
In Case 1, callback reponseaction will fire normally. But if I comment the following code:
```
            client.On("v1/chat/enter", reponseaction);
            await client.EmitAsync("v1/chat/enter", Encoding.UTF8.GetBytes(Test));
```
and replace them with :
`await client.EmitAsync("v1/chat/enter", reponseaction,Encoding.UTF8.GetBytes(Test));`

callback reponseaction will not fire.  Can you help me to point out why the   callback reponseaction will not fire when I use 
`await client.EmitAsync("v1/chat/enter", reponseaction,Encoding.UTF8.GetBytes(Test));`

thanks a lot.
@doghappy

**Comment by doghappy** [comment]
### Case 1 works

Let's check the server code

```ts
    socket.on("v1/chat/enter", (msg2) => {
        console.log("v1");
        console.log(`${msg2.toString()}`);
        const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
        socket.emit("v1/chat/enter", binaryMessage2);
    });
```

`socket.emit("v1/chat/enter", binaryMessage2);` means that the server emits an event to the client, In this case, you need to use `client.On("v1/chat/enter", reponseaction);` to listen to this event.

### Case 2 does not work

```cs
await client.EmitAsync("v1/chat/enter", reponseaction, Encoding.UTF8.GetBytes(Test));
```

It means that the server passes some parameters to the client, and when the client receives them, `reponseaction` will be called.

Usually it is used with the following code:

**Server**

```ts
    socket.on("v1/chat/enter", (msg2, fn) => {
        console.log("v1");
        console.log(`${msg2.toString()}`);
        const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
        fn(binaryMessage2);
    });
```

**Comment by lzd6696** [comment]
> ### Case 1 works
> Let's check the server code
> 
> ```ts
>     socket.on("v1/chat/enter", (msg2) => {
>         console.log("v1");
>         console.log(`${msg2.toString()}`);
>         const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
>         socket.emit("v1/chat/enter", binaryMessage2);
>     });
> ```
> 
> `socket.emit("v1/chat/enter", binaryMessage2);` means that the server emits an event to the client, In this case, you need to use `client.On("v1/chat/enter", reponseaction);` to listen to this event.
> 
> ### Case 2 does not work
> ```cs
> await client.EmitAsync("v1/chat/enter", reponseaction, Encoding.UTF8.GetBytes(Test));
> ```
> 
> It means that the server passes some parameters to the client, and when the client receives them, `reponseaction` will be called.
> 
> Usually it is used with the following code:
> 
> **Server**
> 
> ```ts
>     socket.on("v1/chat/enter", (msg2, fn) => {
>         console.log("v1");
>         console.log(`${msg2.toString()}`);
>         const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
>         fn(binaryMessage2);
>     });
> ```
> 
> ### Choose one of the following two ways:
> 1:
> 
> ```cs
> // server
> socket.on("v1/chat/enter", (msg2) => {
>     console.log("v1");
>     console.log(`${msg2.toString()}`);
>     const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
>     socket.emit("v1/chat/enter", binaryMessage2);
> });
> 
> // client
> client.On("v1/chat/enter", reponseaction);
> await client.EmitAsync("v1/chat/enter", Encoding.UTF8.GetBytes(Test));
> ```
> 
> 2:
> 
> ```cs
> // server
> socket.on("v1/chat/enter", (msg2, fn) => {
>     console.log("v1");
>     console.log(`${msg2.toString()}`);
>     const binaryMessage2 = Buffer.from(msg2.toString() + " - server", "utf-8");
>     fn(binaryMessage2);
> });
> 
> // client
> await client.EmitAsync("v1/chat/enter", reponseaction, Encoding.UTF8.GetBytes(Test));
> ```

Hi :

OK, I get it. Thanks for your help.
