### ISSUE TITLE
Some received socket.io callback packet not  processed by library.

### ISSUE THREAD

**Issue by lzd6696** [doghappy/socket.io-client-csharp#67]
Hi : It's me again.  @doghappy 

First, thanks your quick response for my previous question.

I like your library and i use your library for my working project recently.

I have some issue about catch certain socket.io event's callback on the target server.

Please consider the following socket.io communication captured by fiddler:

![csharp](https://user-images.githubusercontent.com/42199635/87136952-c86f2480-c2ce-11ea-8824-4c5024e2dbb8.jpg)

in ID 10 and 11, i send a "v1/chat/enter" event packet to server, then server response ID 12~19

ID 14 and 15 are server "v1/chat/enter" event's callback response.

I use the following code snippet to catch the callback:

```
            Action<SocketIOResponse> reponseaction2a = async delegate (SocketIOResponse ack)
            {
                userEnterChatAck = EnterChatAck.Parser.ParseFrom(ack.InComingBytes[0].ToArray());

                msgcount = userEnterChatAck.Messages.Count;

            };
            await client.EmitAsync("v1/chat/enter", reponseaction2a, userEnterChatPacket.ToByteArray());

```

But i fail to catch it.

Then i write a node.js socket.io client by type script. below is my code snippet to catch  "v1/chat/enter" callback:

```
            beanfunsocket.emit("v1/chat/enter", bfenterchateventbuffer , pbResultPayload => {

                console.log("enter chat callback.");
                var enterchatackresult = Beanfun.chat.v1.EnterChatAck.decode(pbResultPayload);

                var lastupdate = enterchatackresult.chatsLastUpdated;
                isenterchat = true;
                console.log("chat last update =" + lastupdate);

            });

```
Surprisingly, node.js socket.io client can catch the callback send by server. 

below is success result screenshot.
![csharp1](https://user-images.githubusercontent.com/42199635/87137706-ebe69f00-c2cf-11ea-991e-0ab9562314f7.jpg)

I try to trace into your library for days, but i failed to find a clue. 
I suspect ID 14 and 15 are not received or processed by library.
but ID 14 and 15 are send by server indeed and received by my node.js socket.io client successfully.

Can you help me point out why my c# socket.io client fail to catch the ID 14 and 15 callback ?

I send my fiddler's packet capture file **socketiocompare.saz** as
 attachment **[fiddlerdata.zip]**(https://github.com/doghappy/socket.io-client-csharp/files/4902120/fiddlerdata.zip). 
and I put fiddler setup in the attachment,too. you can install fiddler and double click  **socketiocompare.saz** file,
then double click the request on the left panel to see detail communication info on "websocket" tab in right panel .

if you need any further info, please reply, i will respond asap.

thanks in advance.

**Comment by doghappy** [comment]
Can you create a mini warehouse? Reproduce this problem, so that we can quickly solve the problem.

**Comment by doghappy** [comment]
Can you try the following code?

server:

```js
socket.on("v1/chat/enter", (msg, fn) => {
    const binaryMessage = Buffer.from(msg.toString() + " - server", "utf-8");
    fn(binaryMessage);
});
```

client:

```cs
await socket.EmitAsync("v1/chat/enter", response =>
{
    var buffer = response.GetValue<byte[]>();
    Console.WriteLine(Encoding.UTF8.GetString(buffer));
}, Encoding.UTF8.GetBytes("test"));
```

![image](https://user-images.githubusercontent.com/20038914/87141083-14bd6300-c2d5-11ea-9d32-ae2fc3eeeace.png)

You don't have to deal with `InComingBytes` yourself

**Comment by lzd6696** [comment]
> Can you try the following code?
> 
> server:
> 
> ```js
> socket.on("v1/chat/enter", (msg, fn) => {
>     const binaryMessage = Buffer.from(msg.toString() + " - server", "utf-8");
>     fn(binaryMessage);
> });
> ```
> 
> client:
> 
> ```cs
> await socket.EmitAsync("v1/chat/enter", response =>
> {
>     var buffer = response.GetValue<byte[]>();
>     Console.WriteLine(Encoding.UTF8.GetString(buffer));
> }, Encoding.UTF8.GetBytes("test"));
> ```
> 
> ![image](https://user-images.githubusercontent.com/20038914/87141083-14bd6300-c2d5-11ea-9d32-ae2fc3eeeace.png)
> 
> You don't have to deal with `InComingBytes` yourself

Hi @doghappy : thanks your quick response.

I had try your code, but still not work.
I think main issue is my callback can not be fired by server packet(ex. ID14,ID 15) for some unknown reason.

since the server is not under my control. 
i can not perfectly reproduce server's behavior to you.
so i try to provide detailed client info to you instead.

i am appreciate if you can provide some ideas about this issue.

**Comment by lzd6696** [comment]
Hi @doghappy : 

by the way : I put some debug info on
WebSocketClient/ClientWebSocket.cs  

```
        private async Task ListenAsync()
        {
            var buffer = new byte[ReceiveChunkSize];
            while (_ws.State == WebSocketState.Open)
            {
                var stringResult = new StringBuilder();
                var binaryResult = new List<byte>();
                WebSocketReceiveResult result;
                do
                {
                    result = await _ws.ReceiveAsync(new ArraySegment<byte>(buffer), _connectionToken.Token);
#if DEBUG
                    Trace.WriteLine($"{DateTime.Now} RecvResult--{result.Count}");
#endif
```

and here's the output:
Debug Trace:
2020/7/10  07:31:47 RecvResult--85
2020/7/10 07:31:47 Text Recv--0{"sid":"LErFd-zUsqfh4IL4AABk","upgrades":[],"pingInterval":25000,"pingTimeout":5000}
⬇ 2020/7/10  07:31:47 Recv--0{"sid":"LErFd-zUsqfh4IL4AABk","upgrades":[],"pingInterval":25000,"pingTimeout":5000}
2020/7/10 07:31:47 RecvResult--2
2020/7/10  07:31:47 Text Recv--40
⬇ 2020/7/10  07:31:47 Recv--40
⬆ 2020/7/10  07:31:47 Send--451-0["v1/login",{"_placeholder":true,"num":0}]
⬆ 2020/7/10  07:31:47 Send--Binary message
2020/7/10  07:31:47 RecvResult--36
2020/7/10  07:31:47 Text Recv--461-0[{"_placeholder":true,"num":0}]
⬇ 2020/7/10  07:31:47 Recv--461-0[{"_placeholder":true,"num":0}]
2020/7/10  07:31:47 RecvResult--23
⬇ 2020/7/10  07:31:47 Recv--Binary message
⬇ 2020/7/10  07:31:47 Recv--23
⬆ 2020/7/10  07:31:47 Send--430[]
2020/7/10  07:31:50 RecvResult--49
⬆ 2020/7/10  07:31:50 Send--451-1["v1/chat/enter",{"_placeholder":true,"num":0}]
2020/7/10  07:31:50 Text Recv--451-["v1/snapshot",{"_placeholder":true,"num":0}]
⬆ 2020/7/10  07:31:50 Send--Binary message
⬇ 2020/7/10  07:31:50 Recv--451-["v1/snapshot",{"_placeholder":true,"num":0}]
2020/7/10  07:31:50 RecvResult--797
⬇ 2020/7/10  07:31:50 Recv--Binary message
⬇ 2020/7/10  07:31:50 Recv--797
Event Recv =v1/snapshot
2020/7/10  07:31:51 RecvResult--55
2020/7/10  07:31:51 Text Recv--451-88["v1/read/receive",{"_placeholder":true,"num":0}]
⬇ 2020/7/10 07:31:51 Recv--451-88["v1/read/receive",{"_placeholder":true,"num":0}]

I don't see any ID 14.15 Packet received.

Can you provide your idea about this?

**Comment by doghappy** [comment]
I tried to write some code, but I still can't reproduce it. Is your service public on the Internet and allowed me to access it?

**About the code to try to reproduce:**

server:

```js
    socket.on("v1/login", (msg, fn) => {
        console.log(msg);
        const token = Buffer.from("token", "utf-8");
        fn(token);

        const binaryMessage = Buffer.from("v1/read/receive", "utf-8");
        socket.emit("v1/read/receive", binaryMessage)
    });

    socket.on("v1/chat/enter", (msg, fn) => {
        const binaryMessage = Buffer.from(msg.toString() + " - server", "utf-8");
        fn(binaryMessage);
    });
```

client:

```cs
socket.On("v1/read/receive", response =>
{
    var buffer = response.GetValue<byte[]>();
    Console.WriteLine(Encoding.UTF8.GetString(buffer));
});

byte[] loginBuffer = Encoding.UTF8.GetBytes("v1/login");
await socket.EmitAsync("v1/login", async response =>
{
    var buffer = response.GetValue<byte[]>();
    Console.WriteLine(Encoding.UTF8.GetString(buffer));
    await response.CallbackAsync();
}, loginBuffer);

byte[] enterBuffer = Encoding.UTF8.GetBytes("v1/chat/enter");
await socket.EmitAsync("v1/chat/enter", async response =>
{
    var buffer = response.GetValue<byte[]>();
    Console.WriteLine(Encoding.UTF8.GetString(buffer));
    await response.CallbackAsync();
}, enterBuffer);
```

![image](https://user-images.githubusercontent.com/20038914/87214637-09b01480-c361-11ea-8c06-4c7836d25797.png)

**Comment by lzd6696** [comment]
Hi @doghappy   :  

if you need target socket.io server for futher testing, i put in 
[url.zip](https://github.com/doghappy/socket.io-client-csharp/files/4906201/url.zip)

I think it can be connected from internet. let me know if you can't connect to it.

thanks in advance.

**Comment by doghappy** [comment]
Thank you very much for your issue, I will fix it soon.

**Comment by doghappy** [comment]
If you want to use it as soon as possible, you can modify part of the code. I need to write some test code, the NuGET package will be released at a later time.

![image](https://user-images.githubusercontent.com/20038914/87215383-ae822000-c368-11ea-9b99-64f6f8c353c6.png)

**Comment by lzd6696** [comment]
> If you want to use it as soon as possible, you can modify part of the code. I need to write some test code, the NuGET package will be released at a later time.
> 
> ![image](https://user-images.githubusercontent.com/20038914/87215383-ae822000-c368-11ea-9b99-64f6f8c353c6.png)
HI  @doghappy :  

OK, I got it. I will try this.

by the way, Can you test my target server form internet?

**Comment by doghappy** [comment]
> by the way, Can you test my target server form internet?

yes, I can

**Comment by lzd6696** [comment]
> Thank you very much for your issue, I will fix it soon.



> > by the way, Can you test my target server form internet?
> 
> yes, I can

Hi @doghappy  : 
OK, thanks  for your kindly and quick response, I am appreciated.

**Comment by lzd6696** [comment]
> If you want to use it as soon as possible, you can modify part of the code. I need to write some test code, the NuGET package will be released at a later time.
> 
> ![image](https://user-images.githubusercontent.com/20038914/87215383-ae822000-c368-11ea-9b99-64f6f8c353c6.png)

Hi @doghappy : 
I had modify the part you mention, i think it works.
I will wait your official release to Nuget and testing again.
I think i will close the issue for that time.
thanks a lot, you saved my whole day.

**Comment by doghappy** [comment]
I have released and published to NuGet. Thanks again for your issue

**Comment by lzd6696** [comment]
> I have released and published to NuGet. Thanks again for your issue

Hi: I had download from nuget and tested .
i think it works.
thanks.
