### ISSUE TITLE
Ignore ssl certificate errors

### ISSUE THREAD

**Issue by a35096** [doghappy/socket.io-client-csharp#68]
Hello, is there any way to not verify the SSL certificate when using socket io troughth a SSL connection?
When I try I get the following errors:

System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server
  HttpRequestException: The SSL connection could not be established, see inner exception.
  AuthenticationException: The remote certificate is invalid according to the validation procedure.

**Comment by doghappy** [comment]
I am looking for a solution, but I don't know how to configure the server to make it reproduce. Can I access your service, or can you create some code for easy reproduction?

**Comment by a35096** [comment]
The server is written in Python using Flask. But the certificate that I'm using is self-signed. In some frameworks on the client side is possible to disable the verification of the SSL. I'm wondering how to tho in this one.

**Comment by doghappy** [comment]
I have done some research and haven't found the best solution yet.
The SoketIOClient target framework is `.NET standard 2`, I can't use the `RemoteCertificateValidationCallback` property, which is available in .NETStandard 2.1.

![image](https://user-images.githubusercontent.com/20038914/88021308-d25f1600-cb5f-11ea-88c5-ff6496d11741.png)

![image](https://user-images.githubusercontent.com/20038914/88021230-b8bdce80-cb5f-11ea-8422-f5f53f410cd5.png)

**Comment by a35096** [comment]
I will do some research and try figure it out. If i find something I'll report to you

**Comment by doghappy** [comment]
If you upgrade to the latest version `2.0.2.3`, You can do this

first you need create a class

```
using SocketIOClient.Packgers;
using System.Net.WebSockets;

namespace SocketIOClientSample
{
    class NetCoreWebSocketClient : SocketIOClient.WebSocketClient.ClientWebSocket
    {
        public NetCoreWebSocketClient(SocketIO io, PackgeManager parser) : base(io, parser) { }

        public override ClientWebSocket CreateClient()
        {
            var socket = new ClientWebSocket();
            // Please do not use in production environment
            socket.Options.RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) => true;
            return socket;
        }
    }
}
```

after that, replace the Socket object

```cs
var uri = new Uri("https://localhost:11000");

var socket = new SocketIO(uri, new SocketIOOptions
{
    Query = new Dictionary<string, string>
    {
        {"token", "io" }
    },
    ConnectionTimeout = TimeSpan.FromSeconds(10)
});

socket.Socket = new NetCoreWebSocketClient(socket, new SocketIOClient.Packgers.PackgeManager(socket));
```

**Comment by neumartin** [comment]
Hi!, in version 2.1.5 I haven't **SocketIOClient.WebSocketClient.ClientWebSocket**
I only have **SocketIOClient.WebSocketClient.IWebSocketClient**
How can I do to avoid SSL verification?
Thanks!!

**Comment by doghappy** [comment]
[cid:image001.png@01D70C2B.44212970]

I'm sure they are all made public, I can't reproduce your problem. If this problem still bothers you, please create a reproducible repo.

---
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

发件人: neumartin<mailto:notifications@github.com>
发送时间: 2021年2月26日 4:12
收件人: doghappy/socket.io-client-csharp<mailto:socket.io-client-csharp@noreply.github.com>
抄送: HeroWong<mailto:hero_wong@outlook.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [doghappy/socket.io-client-csharp] Ignore ssl certificate errors (#68)


Hi!, in version 2.1.5 I haven't SocketIOClient.WebSocketClient.ClientWebSocket
I only have SocketIOClient.WebSocketClient.IWebSocketClient
How can I do to avoid SSL verification?
Thanks!!

―

**Comment by neumartin** [comment]
Hi, 
Now work, I had a problem with NetStandard version.
Thanks!!
