### ISSUE TITLE
OnConnectError and OnConnectTimeout

### ISSUE THREAD

**Issue by PranKe01** [doghappy/socket.io-client-csharp#71]
It would be nice to have the mentioned functions. They seem to be planned - at least I found references in the source code: https://github.com/doghappy/socket.io-client-csharp/blob/0c1d947b420f210a0dbfe95c54ef93e53e2b7d75/src/SocketIOClient/SocketIO.cs#L73

**Comment by doghappy** [comment]
How to trigger [connect_error](https://socket.io/docs/client-api/#Event-%E2%80%98connect-error%E2%80%99-1) and [connect_timeout](https://socket.io/docs/client-api/#Event-%E2%80%98connect-timeout%E2%80%99-1) event in js?

**Comment by PranKe01** [comment]
I am not sure. Previously I was using the library SocketIoClientDotNet. It contained those two events. Now I want to migrate my code, but those two events are missing.

**Comment by PranKe01** [comment]
What is the status here? :)
