### ISSUE TITLE
InvalidOperationException: There is already one outstanding 'SendAsync' call for this WebSocket instance.

### ISSUE THREAD

**Issue by PranKe01** [doghappy/socket.io-client-csharp#73]
I am getting the error message: There is already one outstanding 'SendAsync' call for this WebSocket instance.

Would be nice, if the SocketIOClient would have a queue or something like this, to avoid such an Exception. The Exception is coming from WebSockets library, I think.

**Comment by doghappy** [comment]
I tried to write the following code, but it cannot be reproduced. Can you reproduce it for me?

```cs
await socket.ConnectAsync();

socket.On("hi", response =>
{
    Console.WriteLine($"server: {response.GetValue<string>()}");
});

await Task.Delay(2000);
while (true)
{
    Parallel.For(0, 20, i =>
    {
        socket.EmitAsync("hi", "1").GetAwaiter().GetResult();
    });
    await Task.Delay(1000);
}
````

**Comment by FurtadoT** [comment]
Hello! I'm having the same issue. This code for instance always throw this exception:
```
this.Socket.On(
                "hi",
                response =>
                {
                    new Task(
                        () =>
                        {
                            Thread.Sleep(1000);

                            response.CallbackAsync().GetAwaiter().GetResult();
                        }).Start();

                    this.DoSomeh(response.GetValue<byte[]>());
                });
```
This is a silly example just to demonstrate with 100% accuracy. If we remove this `new Task` thing and just call `response.CallbackAsync().GetAwaiter().GetResult()` the exception can happen too, but with smaller chances;

**Comment by doghappy** [comment]
@FurtadoT Thank you for the code, but I still can't reproduce it, I don't know what I did wrong. Can you provide a minimal reproducible github repository? thank you very much
