### ISSUE TITLE
Getting Socket client session id on connection

### ISSUE THREAD

**Issue by ranjanpr** [doghappy/socket.io-client-csharp#74]
In Javascript i can do get the session id on connection from client side like this.

`var socketConnection = io.connect();
socketConnection.on('connect', function() {
  const sessionID = socketConnection.socket.sessionid; //
  ...
});`

Is there any way to achieve same?

**Comment by doghappy** [comment]
```cs
var socket = new SocketIO();
await socket.ConnectAsync();
await Task.Delay(2000);
Console.WriteLine(socket.Id);
```

or 

```cs
var socket = new SocketIO();
socket.OnConnected += Socket_OnConnected;
await socket.ConnectAsync();

...

private async void Socket_OnConnected(object sender, EventArgs e)
{
    var socket = sender as SocketIO;
    Console.WriteLine("Socket.Id:" + socket.Id);
}
```

**Comment by ranjanpr** [comment]
Thanks @doghappy. I was using pretty old API 1.0.3.13. Did not realize that it has changed a lot. Works after updating to latest nuget package.
