### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by Legacy-WoH** [doghappy/socket.io-client-csharp#75]
When running:
`Task.Run(() => CloseWebSocketAsync()).Wait();`

`static async Task CloseWebSocketAsync()
        {
            await client.DisconnectAsync();
        }`

The console results:
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll

Nothing else is attached to this "client" Socket.IO, its set to fire only once

**Comment by Legacy-WoH** [comment]
Checked server response, the client is being disconnected.
Server is not sending anything back on this event

**Comment by doghappy** [comment]
Which version are you using? I use the latest version, no exception yet

**Comment by Legacy-WoH** [comment]
Controls was being closed to fast, this way it could not find the io connection anymore.
My mistake
