### ISSUE TITLE
A connection cannot be established as the destination computer expressly denied that connection

### ISSUE THREAD

**Issue by tonymanpro** [doghappy/socket.io-client-csharp#76]
All time I try to implement this i get a error:

A connection cannot be established as the destination computer expressly denied that connection

**Comment by doghappy** [comment]
Can you use nodejs to connect to your server? If so, please show some code about the connection?

Btw, which version of SocketIOClient are you using?

**Comment by tonymanpro** [comment]
I use this in my C# Code, the error is that i dont up a service xD.  Is posible  up a service in C#

var client = new SocketIO("http://localhost:11000/");
client.On("hi", response =>
{
    string text = response.GetValue<string>();
});
client.OnConnected += async (sender, e) =>
{
    await client.EmitAsync("hi", ".net core");
};
await client.ConnectAsync();
