### ISSUE TITLE
wait for authentication call to complete

### ISSUE THREAD

**Issue by beauauto** [doghappy/socket.io-client-csharp#79]
I am connecting to a feathersjs server via socket.io interface.
After connection, I make a call to authenticate. After that, I use the connection to do get, set, etc.
However, the async call does not wait for the authentication call to complete. As the result, the following calls fail because of not authenticated error.

What is the proper way to wait until the call to authenticate to go through and make other socket calls thereafter?

await socket.ConnectAsync();

object[] objs = new object[2];
objs[0] = "authentication";
objs[1] = new { strategy = "local", email = "test@test.com", password = "test" };

await socket.EmitAsync("create", response =>
 {
                int c = response.Count;
                for (int i = 0; i < c; ++i)
                {
                    var v = response.GetValue(i).ToString();
                    Console.WriteLine(v);
                }
            }, objs);

objs = new object[1];
objs[0] = "sales";
await socket.EmitAsync("find", objs);

**Comment by doghappy** [comment]
await socket.ConnectAsync();

**Comment by doghappy** [comment]
You need to listen to the Connected event

```cs
static async Task Main(string[] args)
{
    // ...
    socket.OnConnected += Socket_OnConnected;
    await socket.ConnectAsync();
}

private async void Socket_OnConnected(object sender, EventArgs e)
{
    await socket.EmitAsync("create", response =>
    {
        int c = response.Count;
        for (int i = 0; i < c; ++i)
        {
            var v = response.GetValue(i).ToString();
            Console.WriteLine(v);
        }
    }, objs);
}
```

**Comment by beauauto** [comment]
That does the trick. Cool. Thanks.

What is so special about the event handler OnConnected as far as await socket.EmitAsync() is concerned? 

More generally, "await"  in "await socket.EmitAsync()" does not wait for the response method to be called and run through. Does it only wait for the socket to make the call, but pay no attention to what happens in response?

**Comment by doghappy** [comment]
`SocketIOClient` uses WebSocket to send and receive messages, `await socket.ConnectAsync();` means that the WebSocket connection is successful. After that, the SocketIO server will return some configuration information (socketId, PingInterval, PingTimeout). When the client receives a message starting with "40", it means that the SocketIO connection is successful.

https://github.com/socketio/socket.io-protocol#packet

**Comment by beauauto** [comment]
Excellent. All good. Thanks.
