### ISSUE TITLE
Enhancement: TimeOut property and Disposable

### ISSUE THREAD

**Issue by fob71** [doghappy/socket.io-client-csharp#8]
It would great to have a TimeOut property for ConnectAsync() method.

Also a Disposable I think is important.

**Comment by doghappy** [comment]
**Disposable**
It seems that you just need to call `CloseAsync()`

https://github.com/doghappy/socket.io-client-csharp/blob/e3e5905dba138811886b5310e04f10e37c5664e2/SocketIOClient/SocketIO.cs#L85-L100

**Timeout**

It has been added. The default value is `TimeSpan.FromSeconds(30)`

```
var client = new SocketIO("http://localhost:3000")
{
    ConnectTimeout = TimeSpan.FromSeconds(10)
};
```

If timeout occurs, a `TimeoutException` will be thrown
