### ISSUE TITLE
v.2.0.2.5  will get  System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code error

### ISSUE THREAD

**Issue by lzd6696** [doghappy/socket.io-client-csharp#84]
Hi @doghappy :

I had use v.2.0.2.5 to replace v.2.0.2.4 recently.
I found  v.2.0.2.5 will raise 
System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code 
error exception  in my test case code passed using v.2.0.2.4. 

I had check your code changes in  v.2.0.2.5:
            **Monitor.Enter(_lock);
            try
            {
                string dataString = GetDataString(data);
                await EmityCoreAsync(eventName, -1, dataString);
            }
            finally
            {
                Monitor.Exit(_lock);
            }** 

I think using monitor or lock   with  await/async method will cause this exception, 
here is the blog discussing this exception: https://www.rocksolidknowledge.com/articles/locking-and-asyncawait
I think you need using SemaphoreSlim to prevent this exception, but  i am not sure whether  SemaphoreSlim will impact
library performance in highly concurrent multi-thread scenerio or not.

**Comment by doghappy** [comment]
I have released the latest version `2.0.2.6`  
commit: https://github.com/doghappy/socket.io-client-csharp/commit/fe71ee89085e24c73fe77fb62fb95b0bccb75dd5

Thanks very much
