### ISSUE TITLE
Don't throw Exception

### ISSUE THREAD

**Issue by PranKe01** [doghappy/socket.io-client-csharp#88]
https://github.com/doghappy/socket.io-client-csharp/blob/0ab1b494f5fa7fbad195d084f323ce10eb66d4d8/src/SocketIOClient/WebSocketClient/ClientWebSocket.cs

In this code an Exception type is thrown. Catching System.Exception seems like an efficient way to handle multiple possible exceptions. Unfortunately, it traps all exception types, including the ones that were not intended to be caught. To prevent any misunderstandings, the exception filters should be used. Alternatively each exception type should be in a separate catch block.

That's why I ask if you can use a different exception type, or create a new one for that case :)

**Comment by doghappy** [comment]
Thank you for your guidance, you taught me better programming habits.

commit: https://github.com/doghappy/socket.io-client-csharp/commit/7ae3752d0c1a6256653f0b73965ddc5795b79fc1

**Comment by PranKe01** [comment]
There are still some "plain" Exceptions thrown. For example here: https://github.com/doghappy/socket.io-client-csharp/blob/59a83b9168d5b36036bdda3ffd971cfe8c2c65ca/src/SocketIOClient.NetFx/WebSocketClient/WebSocketSharpClient.cs

Or here: https://github.com/doghappy/socket.io-client-csharp/blob/59a83b9168d5b36036bdda3ffd971cfe8c2c65ca/src/SocketIOClient/WebSocketClient/ClientWebSocket.cs

Search for "throw new Exception".
