### ISSUE TITLE
Client stops responding

### ISSUE THREAD

**Issue by sickkick** [doghappy/socket.io-client-csharp#9]
I am having an issue where the client just stops working after about 60 seconds or less. No disconnect events are fired and no errors.

**Comment by doghappy** [comment]
`1.0.2.3` is available, please update the NuGet package. Fixed

**Comment by Xathz** [comment]
I'm having this issue too. Happens around 60 seconds for me as well.
No disconnect event, no error.
Using version `1.0.2.4`.

**Comment by doghappy** [comment]
Cool :D, I finally found the real reason and killed it. **please upgrade to `1.0.2.5`**

**Comment by Xathz** [comment]
Updated to `1.0.2.5` and it seems to be working as expected.
Thanks for the quick response and fix.
