### ISSUE TITLE
Url path connection problem js to c#

### ISSUE THREAD

**Issue by musicianx2** [doghappy/socket.io-client-csharp#90]
I am new at socket programming.
This is the code I am working on

public async Task socketConnection()
{
    SocketIO client = new SocketIO("http://192.168.0.50:1111'");
    string room = "{\"ct\":\"uFDtTkqxFc5wJ8GTACdCGA==\",\"iv\":\"8919586fbd252a13f8a4b614afd51733\",\"s\":\"d1bb08b1606a6865\"}";
    
    await client.ConnectAsync();
    client.OnConnected += async (sender, e) =>
    {
        await client.EmitAsync("room", room);
        
    };
    client.On("message", response =>
    {
        Console.WriteLine(response);

    });
    Console.ReadKey();
}
This works on local socket but I can't connect live socket. I am getting System.Net.WebSockets.WebSocketException: error

I tried:

SocketIO client = new SocketIO("https://www.armut.com/sapi/socket.io/");
SocketIO client = new SocketIO("https://www.armut.com");
SocketIO client = new SocketIO("https://www.armut.com/sapi/socket.io/socket.io.js");
but no luck.

JavaScript uses this url for connection

var socket = io('https://armut.com', {path:'/sapi/socket.io/'});
What is the equivalent of this code for C#?

**Comment by doghappy** [comment]
```cs
SocketIO client = new SocketIO("https://armut.com", new SocketIOOptions
{
    Path = "/sapi/socket.io/"
});
```

**Comment by musicianx2** [comment]
Worked thanks.
