### ISSUE TITLE
Is ConnectionTimeout used somewhere?

### ISSUE THREAD

**Issue by adversinc** [doghappy/socket.io-client-csharp#91]
We have a problem of underlying socket connection hanging for ages. I've checked the source code and it seems that ConnectionTimeout is not being passed anywhere: basically, WebSocketConnectionOptions are barely used in ConnectAsync(Uri, WebSocketConnectionOptions)

Am I right, and can this be fixed?

**Comment by doghappy** [comment]
Before it was only used by `SocketIOClient.NetFx`, I updated `SocketIOClient` to support `ConnectionTimeout`.

```bash
Install-Package SocketIOClient -Version 2.0.2.8
```

commit: https://github.com/doghappy/socket.io-client-csharp/commit/17e2d6c4ebca13fa3fd3e4649c12370f9b3fd676
