### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by pisipisi** [doghappy/socket.io-client-csharp#92]
I have Socket.IO on IISNode, one Angular client, and one .Net 
The one .Net which's using this nuget always get 400 error on connect. But it's ok if I served socket.io server on localhost.

This is my code.

```cs
public static async Task ConnectAsync()
{
    try
    {
        await client.ConnectAsync();
    } 
    catch (Exception e)
    {
        Console.WriteLine(e.Message);
    }
}
 ```

**Comment by pisipisi** [comment]
After I update to 2.0.2.9 I got "Timeout, please see innerException."

   at SocketIOClient.SocketIO.<ConnectCoreAsync>d__88.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SocketIOClient.SocketIO.<ConnectAsync>d__87.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at DataPump.Socket.<ConnectAsync>d__2.MoveNext() in

**Comment by doghappy** [comment]
How do you configure your nginx? If you configure a subpath for the socket.io service, you need to change your code.

nginx:

```
server {
    listen 11001;
    location /path {
        proxy_pass http://localhost:11000; # Service provided by socket.io in docker
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

socket.io server code:

```js
const io = socket(server, {
    pingInterval: 10000,
    pingTimeout: 5000,
    transports: ["websocket"],
    path: "/path" // Same as nginx subpath
});
```

SocketIOClient:

```cs
            var uri = new Uri("http://192.168.253.129:11001");

            var socket = new SocketIO(uri, new SocketIOOptions
            {
                Query = new Dictionary<string, string>
                {
                    {"token", "io" }
                },
                Path = "/path"
            });
```

**Comment by pisipisi** [comment]
the socket server is on Windows with IIS.
I tried to use SocketIoClientDotNet which was no longer supported, it works fine.

**Comment by pisipisi** [comment]
I set up 2 sample project, 
one using .Net Core, which connect fine and fast.
one using .Net Framework 4.7.2, this failed to connect with 400 error.
Do you have any explanation for that?

**Comment by pisipisi** [comment]
I read this from Microsoft 
`Some of the classes and class elements in the System.Net.WebSockets namespace are supported on Windows 7, Windows Vista SP2, and Windows Server 2008. However, the only public implementations of client and server WebSockets are supported on Windows 8 and Windows Server 2012. The class elements in the System.Net.WebSockets namespace that are supported on Windows 7, Windows Vista SP2, and Windows Server 2008 are abstract class elements. This allows an application developer to inherit and extend these abstract class classes and class elements with an actual implementation of client WebSockets.`


So I replaced your System.Net.WebSockets with System.Net.WebSockets.Managed. it works perfectly. 
So turn out I'm on Windows 10 that's not supported by Websockets on .Net framework.
