### ISSUE TITLE
Please support socket.io v3

### ISSUE THREAD

**Issue by 0gnj3n** [doghappy/socket.io-client-csharp#95]
Greetings.

in your [sample](https://github.com/doghappy/socket.io-client-csharp/blob/master/src/SocketIOClient.Sample/Program.cs), line 55 

`await socket.ConnectAsync();` 

hangs idle. My uri is my local socket.io on node.js (http://localhost:3000).

I have also used snippet from your readme. 

```
client = new SocketIO("http://localhost:3000");
			
client.On("chat message", response =>
{
   string text = response.GetValue<string>();
});
			
client.OnConnected += async (s, ev) =>
{
   await client.EmitAsync("chat message", ".net core");    //it never reaches this point
};
			
try
{
   await client.ConnectAsync();
}
			
catch (Exception ex)
{
  string h = ex.ToString();
}
```

My server is very simple, basically snippet from socket.io page (chat application).

```
var app = require('express')();
var http = require('http').createServer(app);
var io = require('socket.io')(http);

app.get('/', (req, res) => {
    res.sendFile(__dirname + '/index.html');
});

io.on('connection', (socket) => {
    socket.on('chat message', (msg) => {
        console.log('message: ' + msg);
        io.emit('chat message', msg);
    });
	
});

http.listen(3000, () => {
    console.log('listening on *:3000');
});
```
I can easily make that chat work from javascript,

```
        $(function () {
            var socket = io();
            $('form').submit(function (e) {
                e.preventDefault(); // prevents page reloading
                socket.emit('chat message', $('#m').val());
                $('#m').val('');
                return false;
            });
            socket.on('chat message', function (msg) {
                $('#messages').append($('<li>').text(msg));
            });
        });
```

but I have a hard time trying to get pass socket.ConnectAsync();, it is never in connected state + it never goes in OnConnected event when it executes or in your sample it seems it just hangs idle when timeout is not set... I am trying to use your solution as a signaling for WebRTC so any help greatly appreciated.

**Comment by doghappy** [comment]
@0gnj3n  Can you create a github repository with the code above?

**Comment by 0gnj3n** [comment]
> 
> 
> @0gnj3n Can you create a github repository with the code above?

Sure, hope this [helps](https://github.com/0gnj3n/socket.io-signaling).

**Comment by doghappy** [comment]
@0gnj3n SocketIOClient does not support socket.io v3 yet, In future versions, I will support the latest version of socket.io.

But I can be sure that socket.io v2.2.0 is supported

**Comment by doghappy** [comment]
@0gnj3n I [created a PR](https://github.com/0gnj3n/socket.io-signaling/pull/1/files) to your repository and it works.

**Comment by 0gnj3n** [comment]
Thank you, it works.
