### ISSUE TITLE
How to install new version?

### ISSUE THREAD

**Issue by ArkinSolomon** [doghappy/socket.io-client-csharp#97]
Hello,

I was just wondering how to install the new version of this package that supports v3.

Thanks,
Arkin

**Comment by doghappy** [comment]
If you have already installed `SocketIOClient.NetFx`, please uninstall it, then install `SocketIOClient` v2.1.1

If you have already installed `SocketIOClient`, please upgrade to the latest version(v2.1.1) from NuGet

If you haven't installed the above, Please install from NuGet:

```
Install-Package SocketIOClient -Version 2.1.1
```

If the server uses socket.io v3, please set EIO explicitly

```cs
var client = new SocketIO("http://localhost:11000/", new SocketIOOptions
{
    EIO = 4
});
```

**Comment by ArkinSolomon** [comment]
Thanks I just found the new package!
