### ISSUE TITLE
Connet twice when ConnectAsync

### ISSUE THREAD

**Issue by long2ice** [doghappy/socket.io-client-csharp#99]
WIth v2.1.1:

![image](https://user-images.githubusercontent.com/13377178/100993415-59051480-3590-11eb-888c-702605cf8344.png)

![image](https://user-images.githubusercontent.com/13377178/100993432-5dc9c880-3590-11eb-8549-4d6e7bbfba5e.png)

What happened?

**Comment by nav-cng** [comment]
I'm having the same issue, 
![image](https://user-images.githubusercontent.com/67133315/101267612-af4f9e80-37ae-11eb-9683-c8a2508e33b1.png)

**Comment by Legacy-WoH** [comment]
Same issue
![Screenshot_1](https://user-images.githubusercontent.com/9155161/101268926-324e0600-3769-11eb-9ced-3299aab83d5f.jpg)

**Comment by long2ice** [comment]
Downgrade to `v2.0.2.7` solved this temporarily

**Comment by doghappy** [comment]
Try to delete ~`EIO=3`~

If the server uses `socket.io v3`, you need to set `EIO=4`, if the server uses socket.io v2, please don't set EIO

**Comment by PranKe01** [comment]
I am using socket.io v1 server and I did not set EIO=4. I used your sample code with my server and I also get two responses.

**Comment by doghappy** [comment]
> I am using socket.io v1 server and I did not set EIO=4. I used your sample code with my server and I also get two responses.

This library does not support socket.io v1.x

**Comment by PranKe01** [comment]
> > I am using socket.io v1 server and I did not set EIO=4. I used your sample code with my server and I also get two responses.
> 
> This library does not support socket.io v1.x

But it is working (: And I noticed, that when I run the latest solution from github it only shows once. But when I replace with the socketioclient.dll from nugetpackage v2.1.1, it shows twice! So maybe it is time for a new upload to nuget ;)

**Comment by doghappy** [comment]
> > > I am using socket.io v1 server and I did not set EIO=4. I used your sample code with my server and I also get two responses.
> > 
> > 
> > This library does not support socket.io v1.x
> 
> But it is working (: And I noticed, that when I run the latest solution from github it only shows once. But when I replace with the socketioclient.dll from nugetpackage v2.1.1, it shows twice! So maybe it is time for a new upload to nuget ;)

The latest code has no changes compared with `SocketIOClient.dll v2.1.1`, only the `Sample` and `unit tests` are modified

**Comment by nezarfadle** [comment]
I had the same issue when I was using `"socket.io": "2.0.3"` and upgrading to `"socket.io": "4.0.0"` resolved my issue

**Comment by AshotN** [comment]
I am still experiencing this issue with socket.io on version 4, and EIO set to 4
